// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const migrationDatabaseUrl =
  process.env["DIRECT_DATABASE_URL"] || process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7 CLI uses datasource.url for migrations and introspection.
    // Runtime queries continue to use DATABASE_URL in lib/prisma.ts.
    url: migrationDatabaseUrl,
  },
});
