import assert from "node:assert/strict";
import test from "node:test";

import {
  dualComparisonReviewResultSchema,
  verifiedComparisonReviewResultSchema,
} from "../lib/comparisonReview.ts";
import { toSourceGrounding } from "../lib/sourceGrounding.ts";
import { comparisonReviewItems } from "../lib/comparisonReviewItemFeedback.ts";

// A `ComparisonReview` row stores the enriched result and is validated on read
// (app/api/conversations/[conversationId]/comparison-reviews/route.ts). Nothing
// migrates those rows, so any change to the review pipeline has to leave the
// rows already in the database readable -- otherwise a cache hit silently
// falls through to a second paid run, and the user is charged again for a
// review they already have.
//
// These literals are what the schema accepted before the M5 work, byte for
// byte: no per-item id, no reviewer namespace, no telemetry field. They are
// deliberately hand-written rather than produced by the current code, because
// a fixture generated by the code under test can only prove the code agrees
// with itself.

const STORED_SINGLE_REVIEWER_ROW = {
  primary: {
    reviewerModelId: "mistral-medium-3-1",
    result: {
      consensus: [
        {
          text: "Both answers put the length at about 193 km.",
          citations: [
            { responseId: "A", quote: "roughly 193 kilometres", verified: true },
          ],
          verified: true,
        },
      ],
      differences: [
        {
          issue: "Whether the canal carries 12 percent of world trade.",
          positions: [
            {
              responseId: "A",
              position: "States 12 percent.",
              quote: "about 12 percent of world trade",
              verified: true,
            },
            {
              responseId: "B",
              position: "Does not give a figure.",
              quote: "Construction was led by Ferdinand de Lesseps.",
              verified: true,
            },
          ],
        },
      ],
      contradictions: [
        {
          text: "B dates the opening to 1859 while A says 1869.",
          citations: [
            { responseId: "B", quote: "opened in 1859", verified: false },
          ],
          verified: false,
        },
      ],
      missingPoints: ["B never mentions the Red Sea connection."],
      verificationNeeded: ["The opening year."],
      modelAssessments: [
        { responseId: "A", strengths: ["Specific"], cautions: [] },
        { responseId: "B", strengths: [], cautions: ["Unsupported date"] },
      ],
      synthesis: "",
      limitations: ["This review is not external fact verification."],
      confidence: "medium",
      groundingStats: { totalCitations: 4, verifiedCitations: 3 },
    },
  },
  secondary: null,
  agreement: null,
};

const STORED_DUAL_REVIEWER_ROW = {
  ...STORED_SINGLE_REVIEWER_ROW,
  secondary: {
    reviewerModelId: "claude-sonnet-5",
    result: STORED_SINGLE_REVIEWER_ROW.primary.result,
  },
  agreement: {
    confidenceMatches: true,
    primaryConfidence: "medium",
    secondaryConfidence: "medium",
    sharedVerifiedQuoteCount: 2,
  },
};

test("a stored single-reviewer review still parses", () => {
  const parsed = dualComparisonReviewResultSchema.safeParse(
    STORED_SINGLE_REVIEWER_ROW
  );
  assert.equal(parsed.success, true, parsed.error?.message);
  assert.equal(parsed.data.secondary, null);
  assert.equal(parsed.data.agreement, null);
});

test("a stored dual-reviewer review still parses, agreement included", () => {
  const parsed = dualComparisonReviewResultSchema.safeParse(
    STORED_DUAL_REVIEWER_ROW
  );
  assert.equal(parsed.success, true, parsed.error?.message);
  assert.equal(parsed.data.agreement.sharedVerifiedQuoteCount, 2);
});

test("the stored result shape is still the verified-result shape", () => {
  const parsed = verifiedComparisonReviewResultSchema.safeParse(
    STORED_SINGLE_REVIEWER_ROW.primary.result
  );
  assert.equal(parsed.success, true, parsed.error?.message);
});

test("the stored `confidence` field is still read as source grounding, not accuracy", () => {
  const grounding = toSourceGrounding(STORED_SINGLE_REVIEWER_ROW.primary.result);
  assert.equal(grounding.available, true);
  assert.equal(grounding.level, "medium");
  assert.equal(grounding.matchedQuotes, 3);
  assert.equal(grounding.totalQuotes, 4);
  assert.equal(grounding.percent, 75);
});

test("item ids can be derived from a row stored before they existed", () => {
  // The whole reason the id is derived rather than stored: an old row carries
  // no id field, and feedback still has to be able to point at its claims.
  const items = comparisonReviewItems(STORED_SINGLE_REVIEWER_ROW.primary.result);
  assert.equal(items.length, 5);
  assert.ok(items.every((item) => item.id.startsWith("primary:")));
});

test("a review with no citations at all still parses and reports no grounding rate", () => {
  const empty = {
    ...STORED_SINGLE_REVIEWER_ROW,
    primary: {
      ...STORED_SINGLE_REVIEWER_ROW.primary,
      result: {
        ...STORED_SINGLE_REVIEWER_ROW.primary.result,
        consensus: [],
        differences: [],
        contradictions: [],
        groundingStats: { totalCitations: 0, verifiedCitations: 0 },
      },
    },
  };
  const parsed = dualComparisonReviewResultSchema.safeParse(empty);
  assert.equal(parsed.success, true, parsed.error?.message);
  const grounding = toSourceGrounding(parsed.data.primary.result);
  // "medium" is deriveConfidence()'s storage default for an empty citation
  // list, not a measurement, and it must stay dropped rather than displayed.
  assert.equal(grounding.available, false);
  assert.equal(grounding.level, null);
  assert.equal(grounding.percent, null);
});
