import type { Language } from "@/components/LanguageProvider";

export type ChatHelpCopy = {
  statusTitle: string;
  statusDescription: string;
  lockedFilter: string;
  sharedFilter: string;
  lockedBadge: string;
  sharedBadge: string;
  labelsTitle: string;
  labelsDescription: string;
  projectsDescription: string;
  learnMore: string;
  helpAboutStatus: string;
  helpAboutLabels: string;
  helpAboutProjects: string;
  helpAboutPrivate: string;
  helpAboutCredits: string;
  helpAboutAiReview: string;
  helpAboutModelCredits: string;
  labelAssignment: string;
  emptyLabels: Record<"work" | "research" | "personal", string>;
  emptyLabelBody: string;
  labelGuide: string;
  createProject: string;
  privateTitle: string;
  privateDescription: string;
  creditsTitle: string;
  creditsDescription: string;
  lockDescription: string;
  shareDialogTitle: string;
  shareDialogBody: string;
  shareDialogSnapshot: string;
  shareDialogVisibility: string;
  shareDialogConfirm: string;
  aiReviewTitle: string;
  aiReviewDescription: string;
  modelCreditsTitle: string;
  modelCreditsDescription: string;
  quickHelp: string;
  replayTour: string;
  openFullGuide: string;
  tourSteps: Array<{ title: string; body: string }>;
  tourSkip: string;
  tourNext: string;
  tourDone: string;
};

export const chatHelpCopy: Record<Language, ChatHelpCopy> = {
  en: {
    statusTitle: "Status",
    statusDescription: "Filter by the conversation's current protection and sharing state. Password lock shows protected chats that require password verification. Share link active shows chats with a read-only public link; later messages are not added to the existing shared page automatically.",
    lockedFilter: "Password lock",
    sharedFilter: "Share link active",
    lockedBadge: "Password lock",
    sharedBadge: "Share link",
    labelsTitle: "Labels",
    labelsDescription: "Work, Research, and Personal are private classifications stored in this browser. They do not sync automatically to other devices and do not change AI answers or sharing visibility.",
    projectsDescription: "Group related chats into folders. Chats in the same project do not automatically share content, files, or AI memory. Examples: Marketing, Product launch, Customer research.",
    learnMore: "Learn more",
    helpAboutStatus: "About conversation status",
    helpAboutLabels: "About personal labels",
    helpAboutProjects: "About projects",
    helpAboutPrivate: "About Private Mode",
    helpAboutCredits: "About credits",
    helpAboutAiReview: "About AI Review",
    helpAboutModelCredits: "About model credits",
    labelAssignment: "Assign label",
    emptyLabels: {
      work: "No chats have the Work label yet.",
      research: "No chats have the Research label yet.",
      personal: "No chats have the Personal label yet.",
    },
    emptyLabelBody: "Open a conversation's ⋮ menu to assign a label.",
    labelGuide: "How to assign labels",
    createProject: "Create first project",
    privateTitle: "Private Mode",
    privateDescription: "Tomverse does not save the chat history, but questions, context, and attachments may still be sent to the selected AI provider to generate an answer.",
    creditsTitle: "Credits",
    creditsDescription: "Credit use can vary by model class, input length, file size, and whether AI Review is used. Check the estimate before sending.",
    lockDescription: "Requires password verification before opening the chat or performing protected actions such as sharing, downloading, editing, or deleting. This is access control, not content encryption.",
    shareDialogTitle: "Create a read-only share page?",
    shareDialogBody: "The current conversation will be published as a read-only page. Anyone with the link can view it without signing in.",
    shareDialogSnapshot: "Later messages are not added to the existing shared page automatically. Regenerate the share snapshot to publish the latest content.",
    shareDialogVisibility: "Remove sensitive or confidential information before sharing.",
    shareDialogConfirm: "Create share link",
    aiReviewTitle: "AI Review",
    aiReviewDescription: "A separate review model organizes agreements, contradictions, omissions, and items needing verification across completed answers. It does not search external sources, fact-check independently, or guarantee accuracy.",
    modelCreditsTitle: "Model credits",
    modelCreditsDescription: "The number beside each model is its typical base charge. Long input, extracted file content, and advanced reasoning can increase the final charge shown before sending.",
    quickHelp: "Help",
    replayTour: "Show sidebar tour",
    openFullGuide: "Open full guide",
    tourSteps: [
      { title: "Organize with projects", body: "Projects group related chats like folders. They do not create shared memory or context between conversations." },
      { title: "Find chats with labels", body: "Work, Research, and Personal are browser-local labels used only for your own organization." },
      { title: "Filter by current status", body: "Password lock and Share link show a conversation's current protection and sharing state." },
    ],
    tourSkip: "Skip",
    tourNext: "Next",
    tourDone: "Done",
  },
  ko: {
    statusTitle: "상태",
    statusDescription: "대화의 현재 보호 및 공유 상태를 기준으로 필터링합니다. 비밀번호 잠금은 확인이 필요한 보호된 대화만, 공유 링크 활성화는 읽기 전용 공개 링크가 있는 대화만 표시합니다. 공유 이후 메시지는 기존 공유 페이지에 자동 반영되지 않습니다.",
    lockedFilter: "비밀번호 잠금",
    sharedFilter: "공유 링크 활성화",
    lockedBadge: "비밀번호 잠금",
    sharedBadge: "공유 링크",
    labelsTitle: "라벨",
    labelsDescription: "업무·리서치·개인은 현재 브라우저에 저장되는 개인 분류입니다. 다른 기기에 자동 동기화되지 않으며 AI 답변 방식이나 대화 공개 범위에는 영향을 주지 않습니다.",
    projectsDescription: "관련 대화를 폴더처럼 묶어 관리합니다. 같은 프로젝트의 대화가 내용, 파일 또는 AI 메모리를 자동으로 공유하지는 않습니다. 예: 마케팅, 제품 출시, 고객 리서치.",
    learnMore: "자세히 알아보기",
    helpAboutStatus: "대화 상태 도움말",
    helpAboutLabels: "개인 라벨 도움말",
    helpAboutProjects: "프로젝트 도움말",
    helpAboutPrivate: "Private Mode 도움말",
    helpAboutCredits: "크레딧 도움말",
    helpAboutAiReview: "AI Review 도움말",
    helpAboutModelCredits: "모델 크레딧 도움말",
    labelAssignment: "라벨 지정",
    emptyLabels: {
      work: "아직 ‘업무’ 라벨이 지정된 대화가 없습니다.",
      research: "아직 ‘리서치’ 라벨이 지정된 대화가 없습니다.",
      personal: "아직 ‘개인’ 라벨이 지정된 대화가 없습니다.",
    },
    emptyLabelBody: "대화의 ⋮ 메뉴에서 라벨을 지정할 수 있습니다.",
    labelGuide: "대화 라벨 지정 방법 보기",
    createProject: "첫 프로젝트 만들기",
    privateTitle: "Private Mode",
    privateDescription: "Tomverse 대화 기록에는 저장하지 않지만, 답변 생성을 위해 선택한 AI 제공업체에는 질문, 대화 맥락과 첨부 내용이 전송될 수 있습니다.",
    creditsTitle: "크레딧",
    creditsDescription: "모델 등급, 입력 길이, 파일 크기 및 AI Review 사용 여부에 따라 차감 크레딧이 달라질 수 있습니다. 전송 전 예상 사용량을 확인하세요.",
    lockDescription: "대화를 열거나 공유·다운로드·수정·삭제 등 보호된 작업을 수행하기 전에 비밀번호 확인을 요구합니다. 콘텐츠 암호화를 의미하지는 않습니다.",
    shareDialogTitle: "읽기 전용 공유 페이지를 만들까요?",
    shareDialogBody: "현재 대화 내용을 읽기 전용 공개 페이지로 만듭니다. 링크를 가진 사람은 로그인하지 않고 볼 수 있습니다.",
    shareDialogSnapshot: "이후 대화 내용은 기존 공유 페이지에 자동으로 추가되지 않습니다. 최신 내용을 공유하려면 공유 스냅샷을 갱신하세요.",
    shareDialogVisibility: "민감하거나 기밀인 정보는 공유 전에 제거하세요.",
    shareDialogConfirm: "공유 링크 만들기",
    aiReviewTitle: "AI Review",
    aiReviewDescription: "별도의 검토 모델이 여러 답변의 공통점·모순·누락·추가 확인 항목을 정리합니다. 외부 자료를 검색하거나 독립적으로 사실을 검증하거나 정확성을 보증하지 않습니다.",
    modelCreditsTitle: "모델별 크레딧",
    modelCreditsDescription: "모델 옆 숫자는 일반적인 기본 차감량입니다. 긴 입력, 파일에서 추출한 내용과 고급 추론은 전송 전에 표시되는 최종 예상량을 늘릴 수 있습니다.",
    quickHelp: "도움말",
    replayTour: "사이드바 안내 다시 보기",
    openFullGuide: "전체 도움말 보기",
    tourSteps: [
      { title: "프로젝트로 함께 정리", body: "관련 대화를 폴더처럼 묶습니다. 대화 간 메모리나 컨텍스트를 공유하는 기능은 아닙니다." },
      { title: "라벨로 빠르게 찾기", body: "업무·리서치·개인은 현재 브라우저에만 저장되는 개인 분류입니다." },
      { title: "현재 상태로 필터링", body: "비밀번호 잠금과 공유 링크는 대화의 현재 보호·공유 상태를 보여줍니다." },
    ],
    tourSkip: "건너뛰기",
    tourNext: "다음",
    tourDone: "완료",
  },
  zh: {
    statusTitle: "状态",
    statusDescription: "按对话当前的保护和分享状态筛选。密码锁定仅显示需要密码验证的对话；分享链接已启用仅显示带只读公开链接的对话。分享后的新消息不会自动加入现有分享页面。",
    lockedFilter: "密码锁定",
    sharedFilter: "分享链接已启用",
    lockedBadge: "密码锁定",
    sharedBadge: "分享链接",
    labelsTitle: "标签",
    labelsDescription: "工作、研究和个人是保存在当前浏览器中的私人分类，不会自动同步到其他设备，也不会改变 AI 回答或分享范围。",
    projectsDescription: "像文件夹一样整理相关对话。同一项目中的对话不会自动共享内容、文件或 AI 记忆。例如：市场、产品发布、客户研究。",
    learnMore: "了解更多",
    helpAboutStatus: "了解对话状态",
    helpAboutLabels: "了解个人标签",
    helpAboutProjects: "了解项目",
    helpAboutPrivate: "了解 Private Mode",
    helpAboutCredits: "了解积分",
    helpAboutAiReview: "了解 AI Review",
    helpAboutModelCredits: "了解模型积分",
    labelAssignment: "指定标签",
    emptyLabels: { work: "尚无带“工作”标签的对话。", research: "尚无带“研究”标签的对话。", personal: "尚无带“个人”标签的对话。" },
    emptyLabelBody: "请从对话的 ⋮ 菜单指定标签。",
    labelGuide: "查看标签使用方法",
    createProject: "创建第一个项目",
    privateTitle: "Private Mode",
    privateDescription: "Tomverse 不保存聊天记录，但为生成回答，问题、上下文和附件仍可能发送给所选 AI 提供商。",
    creditsTitle: "积分",
    creditsDescription: "模型类别、输入长度、文件大小和 AI Review 都可能改变积分消耗。发送前请查看预计用量。",
    lockDescription: "打开对话或执行分享、下载、编辑、删除等受保护操作前需要密码验证。这是访问控制，并非内容加密。",
    shareDialogTitle: "创建只读分享页面？",
    shareDialogBody: "当前对话将发布为只读公开页面，持有链接的人无需登录即可查看。",
    shareDialogSnapshot: "后续消息不会自动加入现有分享页面。要发布最新内容，请重新生成分享快照。",
    shareDialogVisibility: "分享前请移除敏感或机密信息。",
    shareDialogConfirm: "创建分享链接",
    aiReviewTitle: "AI Review",
    aiReviewDescription: "独立审查模型会整理多个回答的共识、矛盾、遗漏和待核实项。它不会搜索外部资料、独立核验事实或保证准确性。",
    modelCreditsTitle: "模型积分",
    modelCreditsDescription: "模型旁的数字是常见基础消耗。长输入、文件提取内容和高级推理可能提高发送前显示的最终预计用量。",
    quickHelp: "帮助",
    replayTour: "重新查看侧栏指南",
    openFullGuide: "打开完整指南",
    tourSteps: [
      { title: "用项目整理", body: "项目像文件夹一样归类相关对话，但不会在对话间建立共享记忆或上下文。" },
      { title: "用标签查找", body: "工作、研究和个人是只保存在当前浏览器中的私人分类。" },
      { title: "按当前状态筛选", body: "密码锁定和分享链接显示对话当前的保护与分享状态。" },
    ],
    tourSkip: "跳过",
    tourNext: "下一步",
    tourDone: "完成",
  },
  fr: {
    statusTitle: "Statut",
    statusDescription: "Filtrez selon la protection et le partage actuels. Verrouillage par mot de passe affiche les conversations protégées ; Lien de partage actif affiche celles qui ont un lien public en lecture seule. Les nouveaux messages ne sont pas ajoutés automatiquement à la page déjà partagée.",
    lockedFilter: "Verrouillage par mot de passe",
    sharedFilter: "Lien de partage actif",
    lockedBadge: "Verrouillé",
    sharedBadge: "Lien de partage",
    labelsTitle: "Libellés",
    labelsDescription: "Travail, Recherche et Personnel sont des classements privés stockés dans ce navigateur. Ils ne se synchronisent pas automatiquement et ne modifient ni les réponses IA ni le partage.",
    projectsDescription: "Regroupez les conversations comme dans des dossiers. Un projet ne partage pas automatiquement contenu, fichiers ou mémoire IA. Exemples : Marketing, Lancement produit, Recherche client.",
    learnMore: "En savoir plus",
    helpAboutStatus: "À propos du statut",
    helpAboutLabels: "À propos des libellés",
    helpAboutProjects: "À propos des projets",
    helpAboutPrivate: "À propos du mode privé",
    helpAboutCredits: "À propos des crédits",
    helpAboutAiReview: "À propos d’AI Review",
    helpAboutModelCredits: "À propos des crédits modèle",
    labelAssignment: "Attribuer un libellé",
    emptyLabels: { work: "Aucune conversation n’a encore le libellé Travail.", research: "Aucune conversation n’a encore le libellé Recherche.", personal: "Aucune conversation n’a encore le libellé Personnel." },
    emptyLabelBody: "Attribuez un libellé depuis le menu ⋮ d’une conversation.",
    labelGuide: "Voir comment attribuer un libellé",
    createProject: "Créer le premier projet",
    privateTitle: "Mode privé",
    privateDescription: "Tomverse ne conserve pas l’historique, mais la question, le contexte et les pièces jointes peuvent être envoyés au fournisseur IA sélectionné.",
    creditsTitle: "Crédits",
    creditsDescription: "La classe du modèle, la longueur, les fichiers et AI Review peuvent modifier les crédits débités. Vérifiez l’estimation avant l’envoi.",
    lockDescription: "Demande le mot de passe avant l’ouverture ou les actions protégées comme partager, télécharger, modifier ou supprimer. Ce n’est pas un chiffrement du contenu.",
    shareDialogTitle: "Créer une page partagée en lecture seule ?",
    shareDialogBody: "La conversation actuelle devient une page publique en lecture seule, visible sans connexion par toute personne ayant le lien.",
    shareDialogSnapshot: "Les messages ultérieurs ne sont pas ajoutés automatiquement. Régénérez l’instantané pour publier la version récente.",
    shareDialogVisibility: "Retirez les informations sensibles ou confidentielles avant le partage.",
    shareDialogConfirm: "Créer le lien",
    aiReviewTitle: "AI Review",
    aiReviewDescription: "Un modèle de revue structure accords, contradictions, omissions et points à vérifier. Il ne cherche pas de sources externes, ne vérifie pas les faits indépendamment et ne garantit pas l’exactitude.",
    modelCreditsTitle: "Crédits par modèle",
    modelCreditsDescription: "Le nombre près du modèle est le coût de base habituel. Les entrées longues, fichiers et raisonnements avancés peuvent augmenter l’estimation finale.",
    quickHelp: "Aide",
    replayTour: "Revoir le guide de la barre latérale",
    openFullGuide: "Ouvrir le guide complet",
    tourSteps: [
      { title: "Organiser avec les projets", body: "Les projets regroupent les conversations sans créer de mémoire ou de contexte partagé." },
      { title: "Retrouver avec les libellés", body: "Travail, Recherche et Personnel restent des classements locaux à ce navigateur." },
      { title: "Filtrer par statut", body: "Le verrouillage et le lien de partage indiquent l’état actuel de protection et de partage." },
    ],
    tourSkip: "Ignorer",
    tourNext: "Suivant",
    tourDone: "Terminer",
  },
  de: {
    statusTitle: "Status",
    statusDescription: "Filtern Sie nach aktuellem Schutz- und Freigabestatus. Passwortschutz zeigt geschützte Chats; Aktiver Freigabelink zeigt Chats mit öffentlichem Nur-Lese-Link. Spätere Nachrichten erscheinen nicht automatisch auf der bestehenden Freigabeseite.",
    lockedFilter: "Passwortschutz",
    sharedFilter: "Aktiver Freigabelink",
    lockedBadge: "Passwortschutz",
    sharedBadge: "Freigabelink",
    labelsTitle: "Labels",
    labelsDescription: "Arbeit, Recherche und Persönlich sind private, in diesem Browser gespeicherte Kategorien. Sie werden nicht automatisch synchronisiert und ändern weder KI-Antworten noch Freigaben.",
    projectsDescription: "Verwandte Chats wie in Ordnern gruppieren. Inhalte, Dateien oder KI-Gedächtnis werden nicht automatisch geteilt. Beispiele: Marketing, Produktstart, Kundenrecherche.",
    learnMore: "Mehr erfahren",
    helpAboutStatus: "Info zum Chatstatus",
    helpAboutLabels: "Info zu Labels",
    helpAboutProjects: "Info zu Projekten",
    helpAboutPrivate: "Info zum Privatmodus",
    helpAboutCredits: "Info zu Credits",
    helpAboutAiReview: "Info zu AI Review",
    helpAboutModelCredits: "Info zu Modell-Credits",
    labelAssignment: "Label zuweisen",
    emptyLabels: { work: "Noch kein Chat trägt das Label Arbeit.", research: "Noch kein Chat trägt das Label Recherche.", personal: "Noch kein Chat trägt das Label Persönlich." },
    emptyLabelBody: "Weisen Sie ein Label über das ⋮-Menü eines Chats zu.",
    labelGuide: "So werden Labels zugewiesen",
    createProject: "Erstes Projekt erstellen",
    privateTitle: "Privatmodus",
    privateDescription: "Tomverse speichert den Verlauf nicht, doch Frage, Kontext und Anhänge können zur Antworterzeugung an den gewählten KI-Anbieter gesendet werden.",
    creditsTitle: "Credits",
    creditsDescription: "Modellklasse, Eingabelänge, Dateien und AI Review können den Verbrauch verändern. Prüfen Sie die Schätzung vor dem Senden.",
    lockDescription: "Verlangt vor dem Öffnen oder geschützten Aktionen wie Teilen, Herunterladen, Bearbeiten oder Löschen ein Passwort. Dies ist keine Inhaltsverschlüsselung.",
    shareDialogTitle: "Schreibgeschützte Freigabeseite erstellen?",
    shareDialogBody: "Der aktuelle Chat wird als öffentliche Nur-Lese-Seite veröffentlicht und kann mit dem Link ohne Anmeldung angesehen werden.",
    shareDialogSnapshot: "Spätere Nachrichten werden nicht automatisch ergänzt. Erstellen Sie den Snapshot neu, um aktuelle Inhalte zu teilen.",
    shareDialogVisibility: "Entfernen Sie sensible oder vertrauliche Informationen vor dem Teilen.",
    shareDialogConfirm: "Freigabelink erstellen",
    aiReviewTitle: "AI Review",
    aiReviewDescription: "Ein Prüfmodell ordnet Gemeinsamkeiten, Widersprüche, Lücken und Prüfbedarf. Es sucht keine externen Quellen, prüft Fakten nicht unabhängig und garantiert keine Richtigkeit.",
    modelCreditsTitle: "Modell-Credits",
    modelCreditsDescription: "Die Zahl am Modell ist der typische Basiswert. Lange Eingaben, Dateien und erweitertes Reasoning können die finale Schätzung erhöhen.",
    quickHelp: "Hilfe",
    replayTour: "Sidebar-Einführung erneut zeigen",
    openFullGuide: "Vollständige Anleitung öffnen",
    tourSteps: [
      { title: "Mit Projekten ordnen", body: "Projekte gruppieren verwandte Chats, ohne gemeinsames Gedächtnis oder Kontext zu erzeugen." },
      { title: "Mit Labels finden", body: "Arbeit, Recherche und Persönlich bleiben private Kategorien in diesem Browser." },
      { title: "Nach Status filtern", body: "Passwortschutz und Freigabelink zeigen den aktuellen Schutz- und Freigabestatus." },
    ],
    tourSkip: "Überspringen",
    tourNext: "Weiter",
    tourDone: "Fertig",
  },
  es: {
    statusTitle: "Estado",
    statusDescription: "Filtra por el estado actual de protección y uso compartido. Bloqueo con contraseña muestra chats protegidos; Enlace compartido activo muestra chats con enlace público de solo lectura. Los mensajes posteriores no se añaden automáticamente a la página compartida existente.",
    lockedFilter: "Bloqueo con contraseña",
    sharedFilter: "Enlace compartido activo",
    lockedBadge: "Bloqueo",
    sharedBadge: "Enlace compartido",
    labelsTitle: "Etiquetas",
    labelsDescription: "Trabajo, Investigación y Personal son clasificaciones privadas guardadas en este navegador. No se sincronizan automáticamente ni cambian las respuestas de IA o el alcance compartido.",
    projectsDescription: "Agrupa chats como carpetas. Un proyecto no comparte automáticamente contenido, archivos o memoria de IA. Ejemplos: Marketing, Lanzamiento, Investigación de clientes.",
    learnMore: "Más información",
    helpAboutStatus: "Acerca del estado",
    helpAboutLabels: "Acerca de las etiquetas",
    helpAboutProjects: "Acerca de los proyectos",
    helpAboutPrivate: "Acerca del modo privado",
    helpAboutCredits: "Acerca de los créditos",
    helpAboutAiReview: "Acerca de AI Review",
    helpAboutModelCredits: "Acerca de créditos por modelo",
    labelAssignment: "Asignar etiqueta",
    emptyLabels: { work: "Aún no hay chats con la etiqueta Trabajo.", research: "Aún no hay chats con la etiqueta Investigación.", personal: "Aún no hay chats con la etiqueta Personal." },
    emptyLabelBody: "Asigna una etiqueta desde el menú ⋮ de una conversación.",
    labelGuide: "Cómo asignar etiquetas",
    createProject: "Crear el primer proyecto",
    privateTitle: "Modo privado",
    privateDescription: "Tomverse no guarda el historial, pero la pregunta, el contexto y los adjuntos pueden enviarse al proveedor de IA seleccionado para generar la respuesta.",
    creditsTitle: "Créditos",
    creditsDescription: "La clase del modelo, la longitud, los archivos y AI Review pueden cambiar el consumo. Revisa la estimación antes de enviar.",
    lockDescription: "Exige contraseña antes de abrir o realizar acciones protegidas como compartir, descargar, editar o eliminar. No es cifrado del contenido.",
    shareDialogTitle: "¿Crear una página compartida de solo lectura?",
    shareDialogBody: "La conversación actual se publicará como página de solo lectura; quien tenga el enlace podrá verla sin iniciar sesión.",
    shareDialogSnapshot: "Los mensajes posteriores no se añaden automáticamente. Regenera la instantánea para publicar el contenido reciente.",
    shareDialogVisibility: "Elimina información sensible o confidencial antes de compartir.",
    shareDialogConfirm: "Crear enlace",
    aiReviewTitle: "AI Review",
    aiReviewDescription: "Un modelo revisor organiza acuerdos, contradicciones, omisiones y puntos por verificar. No busca fuentes externas, no verifica hechos de forma independiente ni garantiza exactitud.",
    modelCreditsTitle: "Créditos por modelo",
    modelCreditsDescription: "El número junto al modelo es el cargo base típico. Entradas largas, archivos y razonamiento avanzado pueden elevar la estimación final.",
    quickHelp: "Ayuda",
    replayTour: "Volver a ver la guía lateral",
    openFullGuide: "Abrir guía completa",
    tourSteps: [
      { title: "Organiza con proyectos", body: "Los proyectos agrupan chats sin crear memoria o contexto compartido entre ellos." },
      { title: "Encuentra con etiquetas", body: "Trabajo, Investigación y Personal son clasificaciones privadas de este navegador." },
      { title: "Filtra por estado", body: "El bloqueo y el enlace compartido muestran el estado actual de protección y uso compartido." },
    ],
    tourSkip: "Omitir",
    tourNext: "Siguiente",
    tourDone: "Terminar",
  },
  pt: {
    statusTitle: "Estado",
    statusDescription: "Filtre pelo estado atual de proteção e partilha. Bloqueio por palavra-passe mostra chats protegidos; Link de partilha ativo mostra chats com página pública só de leitura. Mensagens posteriores não entram automaticamente na página já partilhada.",
    lockedFilter: "Bloqueio por palavra-passe",
    sharedFilter: "Link de partilha ativo",
    lockedBadge: "Bloqueio",
    sharedBadge: "Link de partilha",
    labelsTitle: "Etiquetas",
    labelsDescription: "Trabalho, Pesquisa e Pessoal são classificações privadas guardadas neste navegador. Não sincronizam automaticamente nem alteram respostas de IA ou visibilidade da partilha.",
    projectsDescription: "Agrupe chats como pastas. Um projeto não partilha automaticamente conteúdo, ficheiros ou memória de IA. Exemplos: Marketing, Lançamento, Pesquisa de clientes.",
    learnMore: "Saber mais",
    helpAboutStatus: "Sobre o estado",
    helpAboutLabels: "Sobre as etiquetas",
    helpAboutProjects: "Sobre os projetos",
    helpAboutPrivate: "Sobre o modo privado",
    helpAboutCredits: "Sobre créditos",
    helpAboutAiReview: "Sobre o AI Review",
    helpAboutModelCredits: "Sobre créditos por modelo",
    labelAssignment: "Atribuir etiqueta",
    emptyLabels: { work: "Ainda não há chats com a etiqueta Trabalho.", research: "Ainda não há chats com a etiqueta Pesquisa.", personal: "Ainda não há chats com a etiqueta Pessoal." },
    emptyLabelBody: "Atribua uma etiqueta no menu ⋮ da conversa.",
    labelGuide: "Como atribuir etiquetas",
    createProject: "Criar o primeiro projeto",
    privateTitle: "Modo privado",
    privateDescription: "O Tomverse não guarda o histórico, mas a pergunta, o contexto e os anexos podem ser enviados ao fornecedor de IA selecionado.",
    creditsTitle: "Créditos",
    creditsDescription: "Classe do modelo, comprimento, ficheiros e AI Review podem alterar o consumo. Confirme a estimativa antes de enviar.",
    lockDescription: "Exige palavra-passe antes de abrir ou executar ações protegidas como partilhar, descarregar, editar ou eliminar. Não é encriptação do conteúdo.",
    shareDialogTitle: "Criar página partilhada só de leitura?",
    shareDialogBody: "A conversa atual será publicada como página só de leitura; qualquer pessoa com o link poderá vê-la sem iniciar sessão.",
    shareDialogSnapshot: "Mensagens posteriores não são adicionadas automaticamente. Gere novamente o snapshot para publicar o conteúdo recente.",
    shareDialogVisibility: "Remova informação sensível ou confidencial antes da partilha.",
    shareDialogConfirm: "Criar link",
    aiReviewTitle: "AI Review",
    aiReviewDescription: "Um modelo revisor organiza consensos, contradições, omissões e pontos a verificar. Não pesquisa fontes externas, não verifica factos de forma independente nem garante exatidão.",
    modelCreditsTitle: "Créditos por modelo",
    modelCreditsDescription: "O número junto do modelo é o custo base típico. Entradas longas, ficheiros e raciocínio avançado podem aumentar a estimativa final.",
    quickHelp: "Ajuda",
    replayTour: "Rever guia da barra lateral",
    openFullGuide: "Abrir guia completo",
    tourSteps: [
      { title: "Organize com projetos", body: "Projetos agrupam chats sem criar memória ou contexto partilhado entre conversas." },
      { title: "Encontre com etiquetas", body: "Trabalho, Pesquisa e Pessoal são classificações privadas deste navegador." },
      { title: "Filtre por estado", body: "Bloqueio e link de partilha mostram o estado atual de proteção e partilha." },
    ],
    tourSkip: "Ignorar",
    tourNext: "Seguinte",
    tourDone: "Concluir",
  },
};
