/**
 * Turning a draft into the forms the Guard's rules are checked against.
 *
 * Contract: the S1 plan's S1f section. A rule that matches "최고" has to match
 * a draft that writes it with a zero-width space in the middle, and a rule that
 * matches "best" has to match "Ьеѕt" in Cyrillic look-alikes and "b3st" in
 * leetspeak. None of those are things a person types by accident; they are what
 * somebody types when a filter is in the way.
 *
 * **The needles are folded by the same functions as the haystack.** That is the
 * whole design. Folding `1` to `i` also folds `l` to `i`, so "leetspeak" and
 * "1eetspeak" and "ieetspeak" are one string -- and a rule written as "leet"
 * becomes "ieet" too, so it still matches. Trying to fold only the text would
 * mean enumerating every spelling of every rule; trying to enumerate variants
 * of the input means a combinatorial explosion for every ambiguous character.
 * Folding both sides collapses that to one comparison.
 *
 * Every variant is checked by every rule, whatever the draft's locale says: a
 * Korean draft can carry an English ban word and a English draft can carry a
 * Korean one, and the locale field is the author's claim rather than a fact
 * about the bytes.
 *
 * Pure: no server-only import, no network, no Prisma.
 */

/**
 * Characters that are invisible, or that change how the text after them reads.
 *
 * Zero-width joiners and non-joiners are legitimate in Indic and emoji
 * sequences and are still refused here, because a marketing caption in the four
 * locales this product publishes in has no use for one -- and the Guard's
 * refusal costs an operator a rewrite, while a false accept costs a published
 * post that says something other than what was reviewed.
 */
const ZERO_WIDTH = /[\u200B-\u200D\u2060\uFEFF\u180E]/u;

/** Left-to-right and right-to-left overrides, isolates and embeddings. */
const BIDI_CONTROL = /[\u061C\u200E\u200F\u202A-\u202E\u2066-\u2069]/u;

/**
 * C0 and C1 controls, less the three a caption may legitimately contain.
 *
 * Tab, newline and carriage return are ordinary in a multi-line caption. Every
 * other control is either invisible or terminal-specific.
 */
const CONTROL = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F]/u;

/**
 * An `@` mention in any of the shapes a platform recognises.
 *
 * Full-width `＠` is folded to `@` by NFKC before this runs, and the small
 * commercial at `﹫` with it, so the pattern only has to know about one. A post
 * this product publishes does not address an account: a mention notifies
 * somebody, and which somebody is a decision no template records.
 */
const MENTION = /(^|[^\w])@[A-Za-z0-9._]{2,}/u;

/**
 * Anything that reads as a web address.
 *
 * Wide on purpose. The one URL a post may carry is assembled by
 * `lib/marketingLinks.ts` from an approved id and attached by the publisher, so
 * a URL *in the generated text* is always something the model produced -- and a
 * model that produces a URL has produced a destination nobody approved. The
 * obfuscations are here because they are what somebody writes when a plain URL
 * is refused: `hxxp`, `example[.]com`, `example(dot)com`.
 */
const URL_LIKE = new RegExp(
  [
    "\\b[a-z][a-z0-9+.-]*://",
    "\\bh[xt]{2}ps?\\b",
    "\\bwww\\d{0,3}\\.",
    // A bare host: a label, a dot, and a plausible TLD. `xn--` covers IDN
    // punycode, which is how a look-alike domain is written once it is encoded.
    "\\b(?:xn--[a-z0-9-]+|[a-z0-9][a-z0-9-]{0,62})\\.(?:com|net|org|io|ai|app|co|kr|cn|tw|hk|jp|us|uk|dev|xyz|link|site|online|shop|store|info|biz|me|tv|cc)\\b",
    // The same, written to survive a filter.
    "\\[\\s*\\.\\s*\\]",
    "\\(\\s*(?:dot|점)\\s*\\)",
    "\\s(?:dot|점)\\s[a-z]{2,}",
  ].join("|"),
  "iu",
);

/** Markdown and HTML link syntax, whatever it points at. */
const LINK_MARKUP = /\[[^\]]*\]\([^)]*\)|<\s*a\b[^>]*>|href\s*=/iu;

/**
 * Text that addresses a reader who is a model rather than a person.
 *
 * A marketing draft is generated by a model from a brief, and a brief that
 * arrived from anywhere outside this system is untrusted text. These are the
 * markers that text uses when it is trying to become an instruction.
 */
const PROMPT_INJECTION = new RegExp(
  [
    "ignore (?:all |any |the )?(?:previous|prior|above)",
    "disregard (?:all |any |the )?(?:previous|prior|above)",
    "system prompt",
    "you are (?:now |a |an )",
    "</?(?:system|assistant|user|instructions?)>",
    "\\[\\s*(?:system|assistant|instructions?)\\s*\\]",
    "이전\\s*(?:지시|명령|프롬프트)",
    "시스템\\s*프롬프트",
    "忽略(?:之前|上述|以上)",
    "系统提示",
  ].join("|"),
  "iu",
);

/** Why a draft is refused before any rule about what it says. */
export const MARKETING_HYGIENE_CODES = Object.freeze([
  "control_character",
  "bidi_control",
  "zero_width",
  "mention",
  "url_like",
  "link_markup",
  "prompt_injection_marker",
] as const);

export type MarketingHygieneCode = (typeof MARKETING_HYGIENE_CODES)[number];

/**
 * Letters that are not the letter they look like.
 *
 * Curated rather than generated: the full Unicode confusables table maps
 * thousands of characters, including many a Korean or Chinese caption uses
 * legitimately, and folding those would make the Korean rules match Korean
 * text at random. What is here is the Cyrillic and Greek that look like Latin
 * in a sans-serif face, which is the set somebody reaches for to write an
 * English ban word that does not look like one.
 *
 * Full-width Latin, mathematical alphanumerics and the enclosed forms are not
 * here because NFKC already folds them, which runs first.
 */
/**
 * The circled and squared letter forms, mapped to the letter they enclose.
 *
 * Generated from their code point ranges rather than typed out, because there
 * are a hundred and four of them and a hand-written table would have holes --
 * which is exactly how `b🅴st` got through the first version of this module.
 * NFKC folds two of these four ranges and leaves the negative forms alone, so
 * the generated table covers all four and the duplicates cost nothing.
 *
 * Symbols rather than letters, so they would otherwise be read as separators
 * and split a word rather than spell one.
 */
function enclosedLatinLetters(): Record<string, string> {
  const map: Record<string, string> = {};
  const starts = [
    0x24b6, // Ⓐ circled capital
    0x24d0, // ⓐ circled small
    0x1f130, // 🄰 squared capital
    0x1f150, // 🅐 negative circled capital
    0x1f170, // 🅰 negative squared capital
  ];
  for (const start of starts) {
    for (let index = 0; index < 26; index += 1) {
      map[String.fromCodePoint(start + index)] = String.fromCharCode(
        "a".charCodeAt(0) + index,
      );
    }
  }
  return map;
}

const CONFUSABLES: Readonly<Record<string, string>> = Object.freeze({
  // Cyrillic
  а: "a", б: "b", в: "b", г: "r", д: "d", е: "e", ж: "x", з: "3", и: "n",
  й: "n", к: "k", л: "n", м: "m", н: "h", о: "o", п: "n", р: "p", с: "c",
  т: "t", у: "y", ф: "o", х: "x", ц: "u", ч: "y", ш: "w", щ: "w", ъ: "b",
  ы: "b", ь: "b", э: "e", ю: "o", я: "r", і: "i", ј: "j", ѕ: "s", ԁ: "d",
  ԛ: "q", ԝ: "w", ё: "e",
  // Greek
  α: "a", β: "b", γ: "y", δ: "d", ε: "e", ζ: "z", η: "n", θ: "o", ι: "i",
  κ: "k", λ: "n", μ: "m", ν: "v", ξ: "e", ο: "o", π: "n", ρ: "p", ς: "s",
  σ: "o", τ: "t", υ: "u", φ: "o", χ: "x", ψ: "y", ω: "w",
  // Latin letters that are not the ASCII one
  ɪ: "i", ʟ: "l", ɴ: "n", ʀ: "r", ᴀ: "a", ᴄ: "c", ᴅ: "d", ᴇ: "e", ɢ: "g",
  ʜ: "h", ᴊ: "j", ᴋ: "k", ᴍ: "m", ᴏ: "o", ᴘ: "p", ᴛ: "t", ᴜ: "u", ᴠ: "v",
  ᴡ: "w", ʏ: "y", ᴢ: "z", ǀ: "l", ı: "i", ɡ: "g",
  ...enclosedLatinLetters(),
});

/**
 * Characters that stand in for letters when somebody is writing around a
 * filter, folded into one class each.
 *
 * `1`, `l` and `i` all become `i`, and `0` and `o` both become `o`, because the
 * point is not to guess which the author meant -- it is to make every spelling
 * one string. The rules are folded by the same function, so a rule containing
 * `l` still matches after its own `l` has become `i`.
 */
const LEET: Readonly<Record<string, string>> = Object.freeze({
  "0": "o", o: "o",
  "1": "i", l: "i", i: "i", "!": "i", "|": "i",
  "3": "e", e: "e",
  "4": "a", "@": "a", a: "a",
  "5": "s", $: "s", s: "s",
  "7": "t", t: "t",
  "8": "b", b: "b",
  "9": "g", g: "g",
  "6": "g",
  "2": "z", z: "z",
});

/**
 * What a reader sees: NFKC applied, and nothing invisible left in it.
 *
 * The invisible characters are removed rather than kept, because a rule that
 * had to allow for one between every pair of letters would be a rule nobody
 * can read. Their *presence* is reported separately by `marketingTextHygiene`
 * and refuses the draft on its own.
 */
const readableForm = (raw: string): string =>
  raw
    .normalize("NFKC")
    .replace(/[\u200B-\u200D\u2060\uFEFF\u180E]/gu, "")
    .replace(/[\u061C\u200E\u200F\u202A-\u202E\u2066-\u2069]/gu, "")
    .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F]/gu, "");

const foldConfusables = (value: string): string =>
  Array.from(value)
    .map((character) =>
      Object.hasOwn(CONFUSABLES, character)
        ? CONFUSABLES[character]
        : character,
    )
    .join("");

const foldLeet = (value: string): string =>
  Array.from(value)
    .map((character) =>
      Object.hasOwn(LEET, character) ? LEET[character] : character,
    )
    .join("");

/**
 * Separators between single characters removed, and nothing else.
 *
 * This is the variant that catches "b e s t" and "b.e.s.t" and "b🅴s🅴t". What
 * it must not do is remove every separator. A global collapse turns "the best"
 * into "thebest", where a rule with a word boundary no longer matches, and --
 * worse in the other direction -- it makes "bestow" and "asbestos"
 * indistinguishable from "best" for any rule that then has to match without
 * boundaries. The S1 plan names both of those as cases the corpus must show are
 * not rejected.
 *
 * So the rule is the plan's own wording: separators *between letters*, where a
 * letter is a run of one. Text spaced out to defeat a filter is a sequence of
 * one-character runs; ordinary prose is not.
 */
const collapseSeparators = (value: string): string => {
  const tokens = value.match(/[\p{L}\p{N}]+/gu);
  if (!tokens) return "";

  const out: string[] = [];
  let run = "";
  for (const token of tokens) {
    if (Array.from(token).length === 1) {
      run += token;
      continue;
    }
    if (run) {
      out.push(run);
      run = "";
    }
    out.push(token);
  }
  if (run) out.push(run);
  return out.join(" ");
};

export type MarketingTextVariants = {
  /** NFKC, invisible characters stripped. What a person would read. */
  readable: string;
  /** Lower-cased with look-alike letters folded to Latin. */
  folded: string;
  /** `folded`, with digit and symbol stand-ins folded into letter classes. */
  leet: string;
  /** `leet`, with every separator removed. */
  collapsed: string;
};

/**
 * The four forms every rule is checked against.
 *
 * Nested rather than parallel: each is the one before it with one more fold
 * applied, so a rule that matches an earlier form matches every later one. That
 * ordering is what makes "checked against all variants" cheap to reason about.
 */
export function marketingTextVariants(raw: string): MarketingTextVariants {
  const readable = readableForm(raw);
  const folded = foldConfusables(readable.toLowerCase());
  const leet = foldLeet(folded);
  return { readable, folded, leet, collapsed: collapseSeparators(leet) };
}

/**
 * The same folds, applied to a rule's own text.
 *
 * Exported because a rule is written as the word a person would write, and the
 * Guard needs it in the form the draft has been folded into. A rule folded by
 * anything other than this would silently stop matching.
 */
export function foldMarketingRuleText(raw: string): MarketingTextVariants {
  return marketingTextVariants(raw);
}

/**
 * What is wrong with the bytes, before anything about the meaning.
 *
 * Returned as a list rather than a first match: a draft carrying both a mention
 * and a URL has two problems, and an operator rewriting it wants both.
 */
export function marketingTextHygiene(raw: string): MarketingHygieneCode[] {
  const codes: MarketingHygieneCode[] = [];

  if (CONTROL.test(raw)) codes.push("control_character");
  if (BIDI_CONTROL.test(raw)) codes.push("bidi_control");
  if (ZERO_WIDTH.test(raw)) codes.push("zero_width");

  // The readable form for the rest: a mention written with a zero-width space
  // after the `@` is still a mention, and the invisible character has already
  // been reported above.
  const readable = readableForm(raw);
  if (MENTION.test(readable)) codes.push("mention");
  if (URL_LIKE.test(readable)) codes.push("url_like");
  if (LINK_MARKUP.test(readable)) codes.push("link_markup");
  if (PROMPT_INJECTION.test(readable)) codes.push("prompt_injection_marker");

  return codes;
}
