// What public marketing may and may not say about imported conversations and
// account memory.
//
// docs/policy/external-conversation-import-and-memory.md §17 calls this a
// release-blocking contract and names this module as its single source. Until
// now the module did not exist, so the contract was a list two people had to
// remember while writing a landing page — and the claims it forbids are
// exactly the ones marketing copy drifts toward on its own, because they are
// the strongest thing the feature *sounds* like it does.
//
// The failure this guards is not a typo. "Your ChatGPT memory, moved over
// perfectly" is a promise the product cannot keep: retrieval is lexical and
// selective (§9), memories are user-approved statements rather than a
// transferred model state (§8), and the answer is generated by whichever
// Tomverse model is selected. Publishing that sentence is a legal and support
// problem before it is a copy problem, which is why §17 blocks a release
// rather than filing a ticket.
//
// Two halves, with different reach, and the difference is stated rather than
// papered over:
//
//   * the *pattern* half below matches Korean and English phrasings — the two
//     languages §17 itself is written in, and the two with decision-grade
//     coverage elsewhere in the policy (§12.3). It scans copy wherever it
//     lives, including copy written outside any registered namespace.
//   * the *structural* half is the claim registry: marketing may only make a
//     claim that appears in ALLOWED_MEMORY_CLAIMS, and a locale supplies the
//     translation of an approved claim rather than inventing one. That half is
//     language-independent, which is what covers zh/fr/de/es/pt — a claim
//     nobody registered cannot acquire a German translation without first
//     acquiring an id here.
//
// Neither half judges translation quality, and neither is a substitute for
// someone reading the page. They catch the specific sentence §17 names.

/** The languages the forbidden-claim patterns below actually cover. */
export const MEMORY_CLAIM_PATTERN_LANGUAGES = ["ko", "en"] as const;

export type AllowedMemoryClaim = {
    /** Stable id. A locale key for this claim is the approved way to say it. */
    id: string;
    /** §17's own wording, kept verbatim as the statement of what is allowed. */
    policyWording: string;
};

/**
 * The five things §17 permits marketing to claim.
 *
 * Wording is quoted from the policy rather than paraphrased: a paraphrase here
 * would quietly become the contract, and the point of a single source is that
 * the document and the code cannot disagree about what was approved.
 */
export const ALLOWED_MEMORY_CLAIMS: readonly AllowedMemoryClaim[] = [
    {
        id: "importPastConversations",
        policyWording: "다른 AI 서비스의 과거 대화를 가져오세요",
    },
    {
        id: "useApprovedMemories",
        policyWording: "검토하고 승인한 기억을 새 대화에 활용합니다",
    },
    {
        id: "referenceAnswerStyle",
        policyWording: "과거 대화에서 선호하는 답변 방식을 참고합니다",
    },
    {
        id: "currentModelUsesContext",
        policyWording:
            "현재 선택한 Tomverse 모델이 과거 맥락을 참고해 답변합니다",
    },
    {
        id: "draftProfileFromImports",
        policyWording:
            "가져온 대화를 기반으로 사용자 정의 AI 프로필 초안을 만듭니다",
    },
];

/** The key under which an approved claim's translation lives in a locale. */
export const MEMORY_MARKETING_NAMESPACE = "marketingMemory";

/** The id of the disclosure §17 requires alongside any of the claims above. */
export const MEMORY_MARKETING_DISCLOSURE_ID = "modelDifferenceNotice";

/**
 * The required disclosure, in the two languages §17 states it in.
 *
 * It is required *with* the claims, not instead of them: the claims are what
 * the feature does, and this is the limit that keeps them true. Marketing that
 * makes an approved claim without it has made an unqualified promise about
 * matching another provider's answers.
 */
export const MEMORY_MARKETING_DISCLOSURE = {
    ko: "과거 대화의 맥락과 사용자가 승인한 기억·답변 스타일을 참고합니다. 새 답변은 현재 선택한 Tomverse 모델이 생성하므로 원래 AI 서비스와 동일하지 않을 수 있습니다.",
    en: "We draw on the context of your past conversations and the memories and answer style you have approved. New answers are generated by the Tomverse model you have selected, so they may differ from the original AI service.",
} as const;

/** Every key the memory-marketing namespace may contain. */
export const MEMORY_MARKETING_KEYS: readonly string[] = [
    ...ALLOWED_MEMORY_CLAIMS.map((claim) => claim.id),
    MEMORY_MARKETING_DISCLOSURE_ID,
];

export type ForbiddenMemoryClaim = {
    /** Stable id, used in failures so the reader is told which rule was hit. */
    id: string;
    /** Why §17 forbids it, in one sentence. */
    reason: string;
    patterns: readonly RegExp[];
};

/**
 * §17's six forbidden categories.
 *
 * The patterns are deliberately narrow. A broad one ("복제") would fire on the
 * product's own honest copy — the import feature legitimately talks about
 * copying conversations *into* Tomverse — and a guard that cries wolf is
 * switched off by the third person who hits it. Each pattern therefore needs
 * the claim's subject (memory, personality, an external provider's name, the
 * hidden prompt) next to the verb, which is what makes it the forbidden claim
 * rather than a neighbouring true one.
 */
export const FORBIDDEN_MEMORY_CLAIMS: readonly ForbiddenMemoryClaim[] = [
    {
        id: "replicatesMemoryOrPersonality",
        reason:
            "Memories are user-approved statements, not a transferred model state; nothing about a personality or a 'brain' is reproduced.",
        patterns: [
            /(기억|인격|성격|두뇌)[^.\n]{0,20}(복제|재현|그대로\s*옮)/,
            /(복제|재현)[^.\n]{0,12}(기억|인격|두뇌)/,
            /\b(clone|replicate|reproduce|recreate|transfer)s?\b[^.\n]{0,30}\b(memory|memories|personality|persona|brain|mind)\b/i,
            /\b(memory|memories|personality|persona|brain)\b[^.\n]{0,20}\b(cloned|replicated|recreated|reproduced)\b/i,
        ],
    },
    {
        id: "losslessTransfer",
        reason:
            "Import is selective and truncates oversized messages (§5.4); nothing about it is lossless or complete.",
        patterns: [
            /(손실\s*없[이는]|무손실)[^.\n]{0,20}(이전|이관|옮|가져)/,
            /100\s*%[^.\n]{0,20}(이전|이관|옮|복원|가져)/,
            /\b(lossless|100\s*%|complete|perfect)\b[^.\n]{0,30}\b(transfer|migration|import|port)\b/i,
            /\b(transfer|migrate|import)s?\b[^.\n]{0,25}\b(everything|all of it|without any loss|nothing is lost)\b/i,
        ],
    },
    {
        id: "identicalAnswerGuarantee",
        reason:
            "The answer is generated by the selected Tomverse model; no external model's output can be guaranteed.",
        patterns: [
            /(동일한|똑같은)\s*(답변|응답)[^.\n]{0,16}(보장|약속)/,
            /(답변|응답)[^.\n]{0,16}(동일|똑같)[^.\n]{0,12}(보장|약속)/,
            /\b(same|identical)\b[^.\n]{0,20}\b(answers?|responses?|output)\b[^.\n]{0,20}\b(guarantee|guaranteed|every time)\b/i,
            /\bguarantee[sd]?\b[^.\n]{0,25}\b(same|identical)\b[^.\n]{0,15}\b(answers?|responses?)\b/i,
        ],
    },
    {
        id: "styleCloneGuarantee",
        reason:
            "Referencing an answer style is not reproducing a named provider's voice; 'just like Claude' promises what cannot be delivered.",
        patterns: [
            /(Claude|ChatGPT|GPT|Gemini|Copilot)\s*(처럼|같이|와\s*똑같|과\s*똑같)/i,
            /(말투|문체|스타일)[^.\n]{0,20}(복제|재현|그대로)/,
            /\b(just|exactly)\s+like\s+(claude|chatgpt|gpt|gemini|copilot)\b/i,
            /\b(sounds?|writes?|talks?|answers?)\s+(just\s+)?like\s+(claude|chatgpt|gemini)\b/i,
        ],
    },
    {
        id: "providerEndorsement",
        reason:
            "No source provider endorses, partners with or certifies this import; implying it is a false affiliation claim.",
        patterns: [
            /(OpenAI|Anthropic|Google)[^.\n]{0,20}(공식|제휴|파트너|인증|보증)/i,
            /(공식|제휴|파트너|인증)[^.\n]{0,16}(OpenAI|Anthropic|Google)/i,
            /\b(official|certified|approved|endorsed|in partnership)\b[^.\n]{0,25}\b(openai|anthropic|google)\b/i,
            /\b(openai|anthropic|google)\b[^.\n]{0,20}\b(partner|partnership|endorsed|certified)\b/i,
        ],
    },
    {
        id: "hiddenPromptRecovery",
        reason:
            "An export contains conversation text; system prompts and hidden instructions are not in it and cannot be recovered.",
        patterns: [
            /(숨은|숨겨진|내부)\s*(프롬프트|지시문|system\s*prompt)[^.\n]{0,20}(복원|추출|재현|확인)/i,
            /\b(hidden|internal|underlying|secret)\s+(system\s+)?prompts?\b[^.\n]{0,25}\b(recover|reveal|extract|reconstruct)/i,
            /\b(recover|reveal|extract|reconstruct)s?\b[^.\n]{0,25}\b(hidden|internal|underlying|secret)\s+(system\s+)?prompts?\b/i,
        ],
    },
];

export type ForbiddenClaimFinding = {
    claimId: string;
    reason: string;
    /** The matched text, so a failure points at the sentence, not the file. */
    match: string;
};

const SENTENCE_BOUNDARY = /[.!?\n。]/;

/** English negators, which precede what they deny. */
const PRECEDING_NEGATION =
    /\b(not|never|isn't|aren't|wasn't|doesn't|don't|didn't|cannot|can't|won't)\b/i;

/** Korean negators, which close the clause they deny. */
const FOLLOWING_NEGATION = /(않|아닙니다|아니라|아니며|아닌|없습니다|없으며|못합니다)/;

/**
 * The sentence a match sits in, plus whether that sentence asserts anything.
 *
 * Marketing pages carry the denial of every claim §17 forbids — "not
 * affiliated with or endorsed by OpenAI or Anthropic" is on the
 * ChatGPT-vs-Claude page today, and it is there precisely to avoid the claim.
 * A guard that reads a disclaimer as the thing it disclaims would force the
 * disclaimers off the page, which is the opposite of what §17 wants. An FAQ
 * question is treated the same way: "Is Tomverse affiliated with OpenAI?"
 * asserts nothing, and the answer below it is scanned on its own.
 */
const assertsTheClaim = (text: string, matchIndex: number, match: string) => {
    let start = matchIndex;
    while (start > 0 && !SENTENCE_BOUNDARY.test(text[start - 1])) start -= 1;
    let end = matchIndex + match.length;
    while (end < text.length && !SENTENCE_BOUNDARY.test(text[end])) end += 1;

    if (text[end] === "?") return false;
    const before = text.slice(start, matchIndex);
    const after = text.slice(matchIndex + match.length, end);
    return !PRECEDING_NEGATION.test(before) && !FOLLOWING_NEGATION.test(after);
};

/** Matches of `pattern` that their own sentence actually asserts. */
const assertedMatches = (text: string, pattern: RegExp): string[] => {
    // A fresh scanner each time: a shared lastIndex across inputs is how a
    // scanner starts skipping matches after the first file.
    const scanner = new RegExp(
        pattern.source,
        pattern.flags.includes("g") ? pattern.flags : `${pattern.flags}g`
    );
    const matches: string[] = [];
    let found = scanner.exec(text);
    while (found) {
        if (assertsTheClaim(text, found.index, found[0])) matches.push(found[0]);
        found = scanner.exec(text);
    }
    return matches;
};

/**
 * Every forbidden claim a piece of copy makes.
 *
 * Returns all of them rather than the first: one bad paragraph usually trips
 * more than one rule, and fixing them one failure at a time is how a rewrite
 * takes six runs.
 */
export const findForbiddenMemoryClaims = (
    text: string
): ForbiddenClaimFinding[] =>
    FORBIDDEN_MEMORY_CLAIMS.flatMap((claim) =>
        claim.patterns.flatMap((pattern) =>
            assertedMatches(text, pattern).map((match) => ({
                claimId: claim.id,
                reason: claim.reason,
                match,
            }))
        )
    );

/**
 * What §17 is about: account memory, and importing from *another AI service*.
 *
 * Two neighbours have to stay outside it. `import` on its own is a TypeScript
 * keyword and every one of these files opens with it. And "대화 가져오기" on
 * its own is the guest-to-account conversation import — a different feature,
 * with no external provider and no memory in it, whose landing copy would
 * otherwise be told to carry a disclosure about answers differing from an AI
 * service it never mentions.
 */
const IMPORT_OR_MEMORY = new RegExp(
    [
        // The noun, not the verb: the AI Review page says a reader has to
        // "직접 기억해야" — remember for themselves — which is not this
        // feature. Conjugation endings are what tell the two apart.
        "기억(?![하해났나력])",
        "메모리",
        "\\bmemor(y|ies)\\b",
        "과거\\s*대화",
        "\\bpast conversations?\\b",
        "(다른\\s*AI|외부|타사|ChatGPT|Claude|Gemini)[^\\n]{0,30}(가져오|불러오|이전)",
        "\\bimport(ed|ing|s)?\\b[^\\n]{0,40}\\b(chatgpt|claude|gemini|another ai)\\b",
    ].join("|"),
    "i"
);

/**
 * Whether a piece of copy claims import or account memory as something the
 * product does. This is what makes §17's disclosure required.
 *
 * Sentence-aware for the same reason the forbidden matcher is, and the case
 * that forced it is real: the chat-workspace guide says a project "is a
 * folder, not … cross-chat memory" and that projects "do not … share … AI
 * memory". Those sentences mention memory in order to deny it, and demanding
 * a personalisation disclosure next to them would attach a promise to a page
 * that carefully makes none.
 */
export const claimsImportOrMemory = (text: string): boolean =>
    assertedMatches(text, IMPORT_OR_MEMORY).length > 0;
