export const SLACK_TEMPLATE_KEYS = [
  "infrastructure_daily",
  "provider_usage_daily",
  "provider_alert",
] as const;

// Slack's special mention syntax. Keep this outside editable templates so every
// managed delivery, including tests, always raises a channel notification.
export const SLACK_ALERT_MENTION = "<!channel>";

export type SlackTemplateKey = (typeof SLACK_TEMPLATE_KEYS)[number];

export type SlackTemplateDefinition = {
  key: SlackTemplateKey;
  name: string;
  description: string;
  enabled: boolean;
  titleTemplate: string;
  bodyTemplate: string;
  allowedVariables: string[];
};

export const DEFAULT_SLACK_TEMPLATES: SlackTemplateDefinition[] = [
  {
    key: "infrastructure_daily",
    name: "Daily infrastructure report",
    description:
      "Railway, R2, PostgreSQL, and Prisma usage snapshot sent daily at 10:30 Australia/Brisbane.",
    enabled: true,
    titleTemplate: "Tomverse infrastructure report · {{localDate}}",
    bodyTemplate:
      "{{statusSummary}}\n*Railway* · projected {{railwayCost}} · credit {{railwayCredit}} · balance {{railwayBalance}}\n*R2* · storage {{r2Storage}} · objects {{r2Objects}} · Class A {{r2ClassA}} · Class B {{r2ClassB}}\n*Database* · sessions {{dbSessions}} · conversations {{dbConversations}} · messages {{dbMessages}} · provider errors 24h {{dbProviderErrors}}\n*Prisma* · operations {{prismaOperations}} · allowance {{prismaAllowance}} · storage {{prismaStorage}}\nGenerated {{generatedAt}}",
    allowedVariables: [
      "localDate",
      "statusSummary",
      "railwayCost",
      "railwayCredit",
      "railwayBalance",
      "r2Storage",
      "r2Objects",
      "r2ClassA",
      "r2ClassB",
      "dbSessions",
      "dbConversations",
      "dbMessages",
      "dbProviderErrors",
      "prismaOperations",
      "prismaAllowance",
      "prismaStorage",
      "generatedAt",
    ],
  },
  {
    key: "provider_usage_daily",
    name: "Daily provider usage report",
    description:
      "Provider status, reported usage, balance, and reconciliation result from the daily usage sync.",
    enabled: true,
    titleTemplate: "Tomverse provider usage · {{date}} UTC",
    bodyTemplate:
      "{{providerRows}}\n*Summary* · failed {{failed}} · skipped {{skipped}} · generated {{generatedAt}} UTC",
    allowedVariables: [
      "date",
      "providerRows",
      "failed",
      "skipped",
      "generatedAt",
    ],
  },
  {
    key: "provider_alert",
    name: "Provider incident alert",
    description:
      "Budget, failure surge, and model incident alert generated by provider monitoring.",
    enabled: true,
    titleTemplate: "{{title}}",
    bodyTemplate: "*Provider:* {{provider}}\n{{detail}}",
    allowedVariables: ["title", "provider", "detail"],
  },
];

export const slackTemplateDefinition = (key: SlackTemplateKey) =>
  DEFAULT_SLACK_TEMPLATES.find((template) => template.key === key)!;

const PLACEHOLDER_PATTERN = /{{\s*([a-zA-Z][a-zA-Z0-9_]*)\s*}}/g;

export const templatePlaceholders = (value: string) =>
  Array.from(value.matchAll(PLACEHOLDER_PATTERN), (match) => match[1]);

export const invalidTemplatePlaceholders = (
  key: SlackTemplateKey,
  ...values: string[]
) => {
  const allowed = new Set(slackTemplateDefinition(key).allowedVariables);
  return Array.from(
    new Set(values.flatMap(templatePlaceholders).filter((name) => !allowed.has(name)))
  );
};

export const renderSlackTemplate = (
  value: string,
  variables: Record<string, string | number>
) =>
  value.replace(PLACEHOLDER_PATTERN, (_match, name: string) =>
    String(variables[name] ?? "-")
  );
