/**
 * Twenty-six of the fifty-two `durable_facts:en` replacements.
 *
 * `.github/audits/memory-eval-gold-contract-2026-08-27.md` §12.1 and §12.10.
 * The same B+ reason as tranches 2 and 3, and `movedBecause` records the
 * reading each one contributed.
 *
 * ## English overlap is measured over a smaller set
 *
 * The overlap check splits English on spaces and divides by the smaller of
 * the two token sets. These conversations are two or three short turns, so a
 * replacement that keeps the original's sentence scaffolding and swaps the
 * nouns scores far above the 0.45 cap -- six of tranche 3's first drafts did,
 * one at 0.71. So these change what happens in the exchange and not only what
 * it is about: which turn carries the correction, who names the fallback,
 * whether the fact opens the sentence or follows its instruction.
 *
 * ## One of these moved for evidence, not for polarity
 *
 * `succ-durable-en-20`'s gold needed «father» from the first turn and
 * «evening» from the third, so no anchor quote could cover the whole fact.
 * Its replacement puts both values in one user turn, which is the point of
 * the case, and affirms the carer relationship rather than denying a period:
 * a negated gold whose values are a cause and a time of day is the
 * under-specified shape the contract rules out.
 *
 * **Not wired into any registry.** `succ-4` is assembled once all 103 exist.
 *
 * Every gold here has its `polarity`, `evidenceMessageId` and `evidenceQuote`
 * written out and reviewed one at a time
 * (.github/audits/memory-eval-gold-contract-2026-08-27.md §12.11). The anchor
 * ids were generated by locating the one user message holding each quote, and
 * the generator refused any gold whose quote sat in none or in more than one.
 */

import type { Succ4Replacement } from "@/lib/memoryEvalSucc4Replacements/tranche1";

export const SUCC4_TRANCHE_4: readonly Succ4Replacement[] = [
    {
        originalId: "succ-durable-en-3",
        movedBecause:
            "Read during the 121: a trade and the single piece of equipment that caps " +
            "it, off one turn, where the second gold's value sits in a fragment rather " +
            "than a clause.",
        boundary:
            "A trade and the one piece of equipment that bounds it, two affirmed golds " +
            "off one user turn.",
        differsBy:
            "Picture framing and a vacuum press rather than baking and an oven, and the " +
            "cap is stated as time per sheet rather than as headcount.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-404",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "occupation",
                    polarity: "affirmed",
                    factValueAll: ["framer"],
                    evidence: {
                        evidenceMessageId: "succ-b407-1-m1",
                        evidenceQuote:
                            "I'm a picture framer working out of a garage.",
                    },
                    expectedDisposition: "bulk_safe",
                },
                {
                    id: "e2",
                    kind: "constraint",
                    polarity: "affirmed",
                    factValueAll: ["vacuum press"],
                    evidence: {
                        evidenceMessageId: "succ-b407-1-m1",
                        evidenceQuote:
                            "One vacuum press, and it takes an hour a sheet.",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-1",
                    title: "one press",
                    messages: [
                        {
                            externalMessageId: "succ-b407-1-m1",
                            role: "user",
                            content:
                                "I'm a picture framer working out of a garage. One " +
                                "vacuum press, and it takes an hour a sheet.",
                        },
                        {
                            externalMessageId: "succ-b407-1-m2",
                            role: "assistant",
                            content:
                                "So throughput is bounded by that press rather than by " +
                                "your hours.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-7",
        movedBecause:
            "Read during the 121, where the emphasis clauses carry no marker and the " +
            "reading had to say the gold asserts the preference rather than the " +
            "repetition.",
        boundary:
            "An invariant personal preference stated with emphasis, so the gold is the " +
            "choice and not the frequency.",
        differsBy:
            "A hotel floor rather than an aeroplane seat, and the preference is stated " +
            "as what is booked and what is refused rather than as a habit repeated.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-405",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "preference",
                    polarity: "affirmed",
                    factValueAll: ["ground floor"],
                    evidence: {
                        evidenceMessageId: "succ-b407-2-m1",
                        evidenceQuote:
                            "I book the ground floor and nothing above it",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-2",
                    title: "never upstairs",
                    messages: [
                        {
                            externalMessageId: "succ-b407-2-m1",
                            role: "user",
                            content:
                                "When it comes to hotels I book the ground floor and " +
                                "nothing above it, without exception.",
                        },
                        {
                            externalMessageId: "succ-b407-2-m2",
                            role: "assistant",
                            content:
                                "Noted. I'll filter out anything upstairs before it " +
                                "reaches you.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-8",
        movedBecause:
            "Read during the 121: a prohibition in the opening turn, restated by the " +
            "assistant and confirmed by the user, where the gold had to be anchored on " +
            "the user's own wording.",
        boundary:
            "A purchasing or usage rule stated as a prohibition, restated by the " +
            "assistant and confirmed in a third turn.",
        differsBy:
            "Installation rather than a subscription, and the rule is given as a " +
            "positive instruction first with the refusal as its reason.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-406",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "constraint",
                    polarity: "negated",
                    factValueAll: ["install"],
                    evidence: {
                        evidenceMessageId: "succ-b407-3-m1",
                        evidenceQuote:
                            "If it has to be installed, I can't use it.",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-3",
                    title: "browser only",
                    messages: [
                        {
                            externalMessageId: "succ-b407-3-m1",
                            role: "user",
                            content:
                                "Keep to things that run in a browser. If it has to be " +
                                "installed, I can't use it.",
                        },
                        {
                            externalMessageId: "succ-b407-3-m2",
                            role: "assistant",
                            content:
                                "So nothing that touches the machine itself.",
                        },
                        {
                            externalMessageId: "succ-b407-3-m3",
                            role: "user",
                            content:
                                "That's it.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-10",
        movedBecause:
            "Read during the 121, where a health fact is volunteered ahead of the topic " +
            "and the reading had to keep it separate from the caution the assistant " +
            "adds.",
        boundary:
            "A medical reaction volunteered pre-emptively and held for review, with the " +
            "assistant noting it while deferring the clinical judgement.",
        differsBy:
            "A latex reaction and dressings rather than a penicillin allergy and " +
            "antibiotics, and the fact is volunteered as a precondition rather than as " +
            "an aside.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-407",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "constraint",
                    polarity: "affirmed",
                    factValueAll: ["latex"],
                    evidence: {
                        evidenceMessageId: "succ-b407-4-m1",
                        evidenceQuote:
                            "latex brings me out in hives",
                    },
                    expectedDisposition: "sensitive_review",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-4",
                    title: "before we go on",
                    messages: [
                        {
                            externalMessageId: "succ-b407-4-m1",
                            role: "user",
                            content:
                                "Before this goes any further: latex brings me out in " +
                                "hives. It matters for anything involving gloves or " +
                                "dressings.",
                        },
                        {
                            externalMessageId: "succ-b407-4-m2",
                            role: "assistant",
                            content:
                                "I'll note it, though whoever treats you should hear it " +
                                "from you directly.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-20",
        movedBecause:
            "The gold's two values sat in different messages — 'father' in the first " +
            "turn and 'evening' in the third — so no anchor quote could cover the fact, " +
            "which is the evidence rule it moved under.",
        boundary:
            "A caring responsibility that removes a recurring part of the week, held " +
            "for review and stated across a three-turn exchange.",
        differsBy:
            "A mother after a stroke rather than a father with dementia, and both " +
            "values sit in one user turn so the anchor quote covers the whole fact. The " +
            "gold affirms the carer relationship rather than denying a period: a " +
            "negated gold whose values are a cause and a time of day is the " +
            "under-specified shape the contract rules out.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-408",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "constraint",
                    polarity: "affirmed",
                    factValueAll: ["mother", "carer"],
                    evidence: {
                        evidenceMessageId: "succ-b407-5-m3",
                        evidenceQuote:
                            "I am my mother's only carer, and that takes every evening.",
                    },
                    expectedDisposition: "sensitive_review",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-5",
                    title: "who I look after",
                    messages: [
                        {
                            externalMessageId: "succ-b407-5-m1",
                            role: "user",
                            content:
                                "My mother moved in after her stroke.",
                        },
                        {
                            externalMessageId: "succ-b407-5-m2",
                            role: "assistant",
                            content:
                                "That will shape what's realistic to plan.",
                        },
                        {
                            externalMessageId: "succ-b407-5-m3",
                            role: "user",
                            content:
                                "It will. I am my mother's only carer, and that takes " +
                                "every evening.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-21",
        movedBecause:
            "Read during the 121, where the instruction clause carries the marker and " +
            "the recurring fact does not, which is the pair the rule separates.",
        boundary:
            "A weekly slot the user is unreachable in, stated as a standing fixture.",
        differsBy:
            "A choir rehearsal on a weekday evening rather than prayers on a Friday " +
            "afternoon, and the user states the slot as already spoken for rather than " +
            "instructing what not to plan.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-409",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "recurring_context",
                    polarity: "affirmed",
                    factValueAll: ["wednesday"],
                    evidence: {
                        evidenceMessageId: "succ-b407-6-m1",
                        evidenceQuote:
                            "Wednesday evenings I'm at choir and my phone is off.",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-6",
                    title: "choir night",
                    messages: [
                        {
                            externalMessageId: "succ-b407-6-m1",
                            role: "user",
                            content:
                                "Wednesday evenings I'm at choir and my phone is off.",
                        },
                        {
                            externalMessageId: "succ-b407-6-m2",
                            role: "assistant",
                            content:
                                "I'll leave that slot alone.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-22",
        movedBecause:
            "Read during the 121: an instruction phrased as a prohibition whose second " +
            "sentence is affirmative, where the gold had to say which of the two it is " +
            "drawn from.",
        boundary:
            "An instruction about manner phrased as a prohibition, with the reason " +
            "given in the same turn.",
        differsBy:
            "Caveats rather than hedging, and the reason is that a checkable answer " +
            "beats a safe one rather than that uncertainty should be named.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-410",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "communication_style",
                    polarity: "negated",
                    factValueAll: ["caveat"],
                    evidence: {
                        evidenceMessageId: "succ-b407-7-m1",
                        evidenceQuote:
                            "Skip the caveats.",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-7",
                    title: "no caveats",
                    messages: [
                        {
                            externalMessageId: "succ-b407-7-m1",
                            role: "user",
                            content:
                                "Skip the caveats. I'd rather have a wrong answer I can " +
                                "check than a safe one I can't.",
                        },
                        {
                            externalMessageId: "succ-b407-7-m2",
                            role: "assistant",
                            content:
                                "I'll give you the claim and leave you to check it.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-23",
        movedBecause:
            "Read during the 121, where «not the summary» is a marked clause beside the " +
            "affirmed one and the label depended on which the gold takes.",
        boundary:
            "A request for more than the answer, with the rejected alternative named in " +
            "the same turn.",
        differsBy:
            "Showing the working rather than asking for length, so what is wanted is " +
            "the reasoning and not more words.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-411",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "verbosity",
                    polarity: "affirmed",
                    factValueAll: ["working"],
                    evidence: {
                        evidenceMessageId: "succ-b407-8-m1",
                        evidenceQuote:
                            "Show your working rather than the conclusion on its own.",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-8",
                    title: "show the steps",
                    messages: [
                        {
                            externalMessageId: "succ-b407-8-m1",
                            role: "user",
                            content:
                                "Assume I'll read all of it. Show your working rather " +
                                "than the conclusion on its own.",
                        },
                        {
                            externalMessageId: "succ-b407-8-m2",
                            role: "assistant",
                            content:
                                "I'll set out the steps as I go.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-26",
        movedBecause:
            "Read during the 121, where «I'm not moving» carries the marker and the " +
            "identity fact does not.",
        boundary:
            "Where the user lives, stated as settled and not about to change.",
        differsBy:
            "Aberdeen rather than Halifax, and the sentence puts the place first as its " +
            "subject rather than the user.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-412",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "identity",
                    polarity: "affirmed",
                    factValueAll: ["aberdeen"],
                    evidence: {
                        evidenceMessageId: "succ-b407-9-m1",
                        evidenceQuote:
                            "Aberdeen has been home since I was born",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-9",
                    title: "home",
                    messages: [
                        {
                            externalMessageId: "succ-b407-9-m1",
                            role: "user",
                            content:
                                "Aberdeen has been home since I was born and it will " +
                                "stay that way.",
                        },
                        {
                            externalMessageId: "succ-b407-9-m2",
                            role: "assistant",
                            content:
                                "I'll keep everything within reach of there.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-38",
        movedBecause:
            "Read during the 121 as an English pair carrying an affirmed gold and a " +
            "negated one in a single sentence.",
        boundary:
            "A qualification plus an explicit refusal of the basics, two golds of " +
            "opposite sign in one sentence.",
        differsBy:
            "Pharmacy and half-lives rather than statistics and p-values, and the " +
            "qualification is a profession rather than a degree.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-413",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "expertise",
                    polarity: "affirmed",
                    factValueAll: ["pharmacist"],
                    evidence: {
                        evidenceMessageId: "succ-b407-10-m1",
                        evidenceQuote:
                            "I trained as a pharmacist",
                    },
                    expectedDisposition: "bulk_safe",
                },
                {
                    id: "e2",
                    kind: "explanation_depth",
                    polarity: "negated",
                    factValueAll: ["half-life"],
                    evidence: {
                        evidenceMessageId: "succ-b407-10-m1",
                        evidenceQuote:
                            "there's no need to tell me what a half-life is",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-10",
                    title: "take it as read",
                    messages: [
                        {
                            externalMessageId: "succ-b407-10-m1",
                            role: "user",
                            content:
                                "I trained as a pharmacist, so there's no need to tell " +
                                "me what a half-life is.",
                        },
                        {
                            externalMessageId: "succ-b407-10-m2",
                            role: "assistant",
                            content:
                                "I'll take the pharmacology as read.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-52",
        movedBecause:
            "Read during the 121: a thing given up and a decision not to replace it, " +
            "where the gold had to say whether it asserts the thing or its absence.",
        boundary:
            "Something given up together with a decision not to replace it, so it is " +
            "denied of the user going forward.",
        differsBy:
            "A landline given up in a move rather than a car sold, the absence opens " +
            "the sentence rather than the act of disposing of it, and the decision is " +
            "stated as deliberate and closed rather than as a conclusion reached.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-414",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "decision",
                    polarity: "negated",
                    factValueAll: ["landline"],
                    evidence: {
                        evidenceMessageId: "succ-b407-11-m1",
                        evidenceQuote:
                            "No landline here since the move, and that was on purpose",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-11",
                    title: "not putting it back",
                    messages: [
                        {
                            externalMessageId: "succ-b407-11-m1",
                            role: "user",
                            content:
                                "No landline here since the move, and that was on " +
                                "purpose — nothing will persuade us back.",
                        },
                        {
                            externalMessageId: "succ-b407-11-m2",
                            role: "assistant",
                            content:
                                "Mobile only, then, for anything that needs a number.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-58",
        movedBecause:
            "Read during the 121, where the network fact is affirmed and the " +
            "instruction that follows it is negated, and [\"internet\"] named the service " +
            "rather than what is wrong with it.",
        boundary:
            "A network limit the user states as a fact about their connection, which " +
            "rules out a class of suggestions.",
        differsBy:
            "A throttled office network and uploads rather than a slow home line and " +
            "streaming, so what is constrained is sending rather than receiving.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-415",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "constraint",
                    polarity: "affirmed",
                    factValueAll: ["throttle"],
                    evidence: {
                        evidenceMessageId: "succ-b407-12-m1",
                        evidenceQuote:
                            "The office wifi throttles anything over a few megabytes",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-12",
                    title: "uploads",
                    messages: [
                        {
                            externalMessageId: "succ-b407-12-m1",
                            role: "user",
                            content:
                                "The office wifi throttles anything over a few " +
                                "megabytes, so uploads are painful.",
                        },
                        {
                            externalMessageId: "succ-b407-12-m2",
                            role: "assistant",
                            content:
                                "I'll favour things that don't need a big upload.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-61",
        movedBecause:
            "Read during the 121, where a figure is affirmed of the user and the second " +
            "sentence denies what assumes more, so the reading had to pick the clause " +
            "the gold is drawn from.",
        boundary:
            "A time budget stated as a number, with what it rules out named in the same turn.",
        differsBy:
            "A per-session ceiling rather than a daily allowance, and the number is " +
            "given as what will not get done rather than as what is available.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-416",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "constraint",
                    polarity: "affirmed",
                    factValueAll: ["20 minute"],
                    evidence: {
                        evidenceMessageId: "succ-b407-13-m1",
                        evidenceQuote:
                            "Anything longer than a 20 minute session won't get done.",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-13",
                    title: "the whole budget",
                    messages: [
                        {
                            externalMessageId: "succ-b407-13-m1",
                            role: "user",
                            content:
                                "Anything longer than a 20 minute session won't get " +
                                "done. That's the whole budget.",
                        },
                        {
                            externalMessageId: "succ-b407-13-m2",
                            role: "assistant",
                            content:
                                "I'll size every step to fit inside that.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-62",
        movedBecause:
            "Read during the 121: a channel denied of the user during a named period, " +
            "where the gold named the channel and left the period to the sentence.",
        boundary:
            "A contact channel the user cannot use during a named part of the day, with " +
            "the fallback named in the same exchange.",
        differsBy:
            "Video calls blocked by the connection rather than phone calls blocked by " +
            "the workplace, and the fallback is stated by the user rather than offered " +
            "by the assistant.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-417",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "constraint",
                    polarity: "negated",
                    factValueAll: ["video"],
                    evidence: {
                        evidenceMessageId: "succ-b407-14-m1",
                        evidenceQuote:
                            "Video is out for me during the day",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-14",
                    title: "not during the day",
                    messages: [
                        {
                            externalMessageId: "succ-b407-14-m1",
                            role: "user",
                            content:
                                "Video is out for me during the day — the connection " +
                                "here won't hold one. Text or nothing until I'm home.",
                        },
                        {
                            externalMessageId: "succ-b407-14-m2",
                            role: "assistant",
                            content:
                                "Then everything goes in writing until the evening.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-63",
        movedBecause:
            "Read during the 121, where «that I can't move» is a marked relative clause " +
            "on an affirmed recurring fact.",
        boundary:
            "A standing commitment the user cannot move, stated as a recurrence.",
        differsBy:
            "A monthly all-day board meeting rather than a weekly two-hour review, so " +
            "the recurrence is monthly and the block is a whole day.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-418",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "recurring_context",
                    polarity: "affirmed",
                    factValueAll: ["tuesday"],
                    evidence: {
                        evidenceMessageId: "succ-b407-15-m1",
                        evidenceQuote:
                            "The first Tuesday of each month is taken by a board meeting",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-15",
                    title: "board day",
                    messages: [
                        {
                            externalMessageId: "succ-b407-15-m1",
                            role: "user",
                            content:
                                "The first Tuesday of each month is taken by a board " +
                                "meeting that runs all day.",
                        },
                        {
                            externalMessageId: "succ-b407-15-m2",
                            role: "assistant",
                            content:
                                "I'll write that day off each month.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-65",
        movedBecause:
            "Read during the 121: a daily fixture affirmed of the user with its " +
            "consequence in the same sentence.",
        boundary:
            "A daily fixture that removes the same stretch of every day.",
        differsBy:
            "A morning dog walk rather than an afternoon school run, so the fixture " +
            "sits at the start of the day rather than breaking its middle.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-419",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "recurring_context",
                    polarity: "affirmed",
                    factValueAll: ["dog", "morning"],
                    evidence: {
                        evidenceMessageId: "succ-b407-16-m1",
                        evidenceQuote:
                            "The dog gets walked at seven each morning",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-16",
                    title: "the first hour",
                    messages: [
                        {
                            externalMessageId: "succ-b407-16-m1",
                            role: "user",
                            content:
                                "The dog gets walked at seven each morning, come what " +
                                "may, and that eats the first hour of the day.",
                        },
                        {
                            externalMessageId: "succ-b407-16-m2",
                            role: "assistant",
                            content:
                                "I'll treat the first hour as gone.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-73",
        movedBecause:
            "Read during the 121, where «Don't just give me the recommendation» is " +
            "marked and the affirmed request follows the dash.",
        boundary:
            "A request for what sits behind the answer, phrased as more than the " +
            "recommendation.",
        differsBy:
            "Naming the rejected alternatives rather than the trade-offs behind the " +
            "pick, so what is asked for is the shortlist rather than the reasoning.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-420",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "explanation_depth",
                    polarity: "affirmed",
                    factValueAll: ["rejected"],
                    evidence: {
                        evidenceMessageId: "succ-b407-17-m1",
                        evidenceQuote:
                            "name the two you rejected and why",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-17",
                    title: "what you rejected",
                    messages: [
                        {
                            externalMessageId: "succ-b407-17-m1",
                            role: "user",
                            content:
                                "When you land on an option, name the two you rejected and why.",
                        },
                        {
                            externalMessageId: "succ-b407-17-m2",
                            role: "assistant",
                            content:
                                "I'll show the discarded options alongside the pick.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-76",
        movedBecause:
            "Read during the 121, where «I've no plans to leave» carries the marker and " +
            "the identity fact does not.",
        boundary:
            "Where the user is based, stated as settled, so suggestions have to be local to it.",
        differsBy:
            "A rural region rather than a city, and the fact is framed by where the " +
            "user's work runs from rather than where they live.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-421",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "identity",
                    polarity: "affirmed",
                    factValueAll: ["wales"],
                    evidence: {
                        evidenceMessageId: "succ-b407-18-m1",
                        evidenceQuote:
                            "Everything I do runs out of a village in mid-Wales.",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-18",
                    title: "where it all runs from",
                    messages: [
                        {
                            externalMessageId: "succ-b407-18-m1",
                            role: "user",
                            content:
                                "Everything I do runs out of a village in mid-Wales. " +
                                "Nothing about that is going to change.",
                        },
                        {
                            externalMessageId: "succ-b407-18-m2",
                            role: "assistant",
                            content:
                                "I'll assume rural mid-Wales for anything practical.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-88",
        movedBecause:
            "Read during the 121 as an English pair whose two golds take opposite signs " +
            "from one sentence.",
        boundary:
            "Long experience plus an explicit refusal of a definition, two golds of " +
            "opposite sign in one sentence.",
        differsBy:
            "Typesetting and kerning rather than photography and aperture, and the " +
            "experience is given as a span of years opening the sentence rather than as " +
            "a profession.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-422",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "expertise",
                    polarity: "affirmed",
                    factValueAll: ["typesetting"],
                    evidence: {
                        evidenceMessageId: "succ-b407-19-m1",
                        evidenceQuote:
                            "Twenty years of typesetting behind me",
                    },
                    expectedDisposition: "bulk_safe",
                },
                {
                    id: "e2",
                    kind: "explanation_depth",
                    polarity: "negated",
                    factValueAll: ["kerning"],
                    evidence: {
                        evidenceMessageId: "succ-b407-19-m1",
                        evidenceQuote:
                            "kerning is not something I need defined",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-19",
                    title: "no need to define it",
                    messages: [
                        {
                            externalMessageId: "succ-b407-19-m1",
                            role: "user",
                            content:
                                "Twenty years of typesetting behind me, so kerning is " +
                                "not something I need defined.",
                        },
                        {
                            externalMessageId: "succ-b407-19-m2",
                            role: "assistant",
                            content:
                                "I'll assume the typographic vocabulary.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-90",
        movedBecause:
            "Read during the 121: an absence of experience denied of the user across " +
            "two sentences, where the gold had to be anchored on the one that states " +
            "it.",
        boundary:
            "An absence of experience the user states about themselves, with an example " +
            "of what they do not know in the same turn.",
        differsBy:
            "Programming rather than investing, and the second sentence names a term " +
            "rather than a product.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-423",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "expertise",
                    polarity: "negated",
                    factValueAll: ["code"],
                    evidence: {
                        evidenceMessageId: "succ-b407-20-m1",
                        evidenceQuote:
                            "I have never written a line of code.",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-20",
                    title: "from scratch",
                    messages: [
                        {
                            externalMessageId: "succ-b407-20-m1",
                            role: "user",
                            content:
                                "I have never written a line of code. Terms like " +
                                "'repository' mean nothing to me.",
                        },
                        {
                            externalMessageId: "succ-b407-20-m2",
                            role: "assistant",
                            content:
                                "I'll assume nothing and define as I go.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-101",
        movedBecause:
            "Read during the 121, where the state adopted is affirmed and «not up for " +
            "revisiting» is the marked clause beside it.",
        boundary:
            "A household decision presented as settled and not open to revisiting.",
        differsBy:
            "An energy tariff rather than a diet, so the decision is about what the " +
            "household buys rather than what it eats.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-424",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "decision",
                    polarity: "affirmed",
                    factValueAll: ["renewable"],
                    evidence: {
                        evidenceMessageId: "succ-b407-21-m1",
                        evidenceQuote:
                            "We moved the household onto a renewable tariff last spring",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-21",
                    title: "settled",
                    messages: [
                        {
                            externalMessageId: "succ-b407-21-m1",
                            role: "user",
                            content:
                                "We moved the household onto a renewable tariff last " +
                                "spring and that is settled.",
                        },
                        {
                            externalMessageId: "succ-b407-21-m2",
                            role: "assistant",
                            content:
                                "I'll take the tariff as fixed.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-108",
        movedBecause:
            "Read during the 121, where the severity and the instruction sit in " +
            "different sentences and the gold had to be anchored on the fact rather " +
            "than the order.",
        boundary:
            "A severe reaction stated with its consequence for what may be suggested, " +
            "held for review.",
        differsBy:
            "An insect sting shaping outdoor plans rather than a food allergy shaping " +
            "menus, and the severity is stated as an outcome rather than named as a " +
            "condition.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-425",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "constraint",
                    polarity: "affirmed",
                    factValueAll: ["bee"],
                    evidence: {
                        evidenceMessageId: "succ-b407-22-m1",
                        evidenceQuote:
                            "Bee stings put me in hospital.",
                    },
                    expectedDisposition: "sensitive_review",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-22",
                    title: "outdoors",
                    messages: [
                        {
                            externalMessageId: "succ-b407-22-m1",
                            role: "user",
                            content:
                                "Bee stings put me in hospital. Anything outdoors has " +
                                "to account for that.",
                        },
                        {
                            externalMessageId: "succ-b407-22-m2",
                            role: "assistant",
                            content:
                                "I'll factor it into anything outdoors.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-109",
        movedBecause:
            "Read during the 121: a condition affirmed of the user whose consequence " +
            "clause is negated, which is the pair the rule separates.",
        boundary:
            "A medical condition that rules out a class of material, held for review.",
        differsBy:
            "Tinnitus ruling out audio with music rather than migraines capping screen " +
            "time, so the constraint is on the medium rather than on duration.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-426",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "constraint",
                    polarity: "affirmed",
                    factValueAll: ["tinnitus"],
                    evidence: {
                        evidenceMessageId: "succ-b407-23-m1",
                        evidenceQuote:
                            "Tinnitus makes anything with background music unusable for me.",
                    },
                    expectedDisposition: "sensitive_review",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-23",
                    title: "no soundtrack",
                    messages: [
                        {
                            externalMessageId: "succ-b407-23-m1",
                            role: "user",
                            content:
                                "Tinnitus makes anything with background music unusable for me.",
                        },
                        {
                            externalMessageId: "succ-b407-23-m2",
                            role: "assistant",
                            content:
                                "I'll keep to material with no soundtrack.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-110",
        movedBecause:
            "Read during the 121: a missing appliance denied of the user's home, where " +
            "the second sentence names what is there instead.",
        boundary:
            "A piece of equipment the user's home does not have, with what stands in " +
            "for it named in the same turn.",
        differsBy:
            "A washing machine rather than an oven, and the alternative is a place to " +
            "go rather than other equipment in the room.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-427",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "constraint",
                    polarity: "negated",
                    factValueAll: ["washing machine"],
                    evidence: {
                        evidenceMessageId: "succ-b407-24-m1",
                        evidenceQuote:
                            "This place came without a washing machine.",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-24",
                    title: "what the flat came with",
                    messages: [
                        {
                            externalMessageId: "succ-b407-24-m1",
                            role: "user",
                            content:
                                "This place came without a washing machine. It's the " +
                                "launderette or nothing.",
                        },
                        {
                            externalMessageId: "succ-b407-24-m2",
                            role: "assistant",
                            content:
                                "I'll plan around a launderette trip.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-111",
        movedBecause:
            "Read during the 121, where [\"capped\"] is a property of the connection and " +
            "the instruction beside it is negated.",
        boundary:
            "A resource ceiling on the user's own equipment, stated as a fact with the " +
            "number beside it.",
        differsBy:
            "Disk space rather than a monthly data cap, so the limit is on what is kept " +
            "rather than on what is transferred.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-428",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "constraint",
                    polarity: "affirmed",
                    factValueAll: ["disk space"],
                    evidence: {
                        evidenceMessageId: "succ-b407-25-m1",
                        evidenceQuote:
                            "Disk space is what's tight here",
                    },
                    expectedDisposition: "bulk_safe",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-25",
                    title: "what's tight",
                    messages: [
                        {
                            externalMessageId: "succ-b407-25-m1",
                            role: "user",
                            content:
                                "Disk space is what's tight here — four gigabytes free " +
                                "on the machine and no more.",
                        },
                        {
                            externalMessageId: "succ-b407-25-m2",
                            role: "assistant",
                            content:
                                "I'll keep anything I suggest inside that.",
                        },
                    ],
                },
            ],
        },
    },
    {
        originalId: "succ-durable-en-112",
        movedBecause:
            "Read during the 121: an ability denied of the user since an operation, " +
            "with the instruction in a second sentence, held for review.",
        boundary:
            "A physical action the user cannot do since an operation, which excludes " +
            "anything that needs it.",
        differsBy:
            "Kneeling after a knee replacement rather than lifting after back surgery, " +
            "so what is excluded is a posture rather than a load; the operation opens " +
            "the sentence as its subject, and the user says what is no use rather than " +
            "instructing what to omit.",
        settledByExistingContract: true,
        replacement: {
            id: "succ-durable-en-429",
            category: "durable_facts",
            language: "en",
            goldCompleteness: "exhaustive",
            expected: [
                {
                    id: "e1",
                    kind: "constraint",
                    polarity: "negated",
                    factValueAll: ["kneel"],
                    evidence: {
                        evidenceMessageId: "succ-b407-26-m1",
                        evidenceQuote:
                            "The knee replacement means I do not kneel any more.",
                    },
                    expectedDisposition: "sensitive_review",
                },
            ],
            conversations: [
                {
                    externalConversationId: "succ-b407-26",
                    title: "since the operation",
                    messages: [
                        {
                            externalMessageId: "succ-b407-26-m1",
                            role: "user",
                            content:
                                "The knee replacement means I do not kneel any more. " +
                                "Steps that start on the floor are no use.",
                        },
                        {
                            externalMessageId: "succ-b407-26-m2",
                            role: "assistant",
                            content:
                                "Everything I suggest will work standing or seated.",
                        },
                    ],
                },
            ],
        },
    },
];
