/**
 * The anchor each staying gold was reviewed against, frozen as a record.
 *
 * `.github/audits/memory-eval-gold-contract-2026-08-27.md` §12.11, approved
 * 2026-08-28.
 *
 * ## Why the proposal stopped being the answer
 *
 * The assembler used to fall back to `proposeAnchor()` — the first user
 * message carrying every fact value, then the first sentence of it that
 * covers them. That is a *candidate*, and adopting it made a defect
 * unfindable: `succ-assistant-en-306` was anchored on the user quoting the
 * assistant's premise back, and `goldEvidenceFailure()` passed it because a
 * quote can name a user message, be an exact span of it and hold the fact's
 * token while supporting the opposite polarity.
 *
 * So the anchor is data now. Automatic selection proposes; this file records
 * what a reviewer accepted; the assembler compares and refuses on any
 * difference. A later change to the heuristic then fails loudly instead of
 * silently re-anchoring 355 golds.
 *
 * ## What these values are
 *
 * They were generated once from the proposal and frozen, because the proposal
 * is exactly what the batch sheets displayed: each row's quote is the text a
 * reviewer read beside the fact and the polarity they assigned. Regenerating
 * them is not how they get corrected — a wrong anchor is corrected by a
 * reading in `readings.ts`, which overrides this file.
 *
 * After `succ-assistant-en-306` and `en-307` left, **no staying gold has a
 * choice of message left in it**: every one has exactly one user message
 * carrying its fact values. Four have a choice of sentence within that
 * message, and all four were flagged `several_sentences_cover_it` and read
 * during the 121. They carry `sentenceChoice` so the choice stays visible.
 */

export type Succ4Anchor = {
    key: string;
    evidenceMessageId: string;
    evidenceQuote: string;
    /** The fact spanned two sentences of the message and one was chosen. */
    sentenceChoice?: true;
};

export const SUCC4_ANCHORS: readonly Succ4Anchor[] = [
    { key: "succ-durable-ko-1:e1", evidenceMessageId: "succ-b101-1-m1", evidenceQuote: "저 갑각류 알레르기 있어서 새우나 게 들어간 건 빼주세요." },
    { key: "succ-durable-ko-3:e1", evidenceMessageId: "succ-b101-3-m1", evidenceQuote: "앞으로 짧게 대답해 주세요." },
    { key: "succ-durable-ko-4:e1", evidenceMessageId: "succ-b101-4-m1", evidenceQuote: "요즘 가계부 앱을 혼자 만들고 있어요." },
    { key: "succ-durable-ko-5:e1", evidenceMessageId: "succ-b101-5-m1", evidenceQuote: "부산 살아요." },
    { key: "succ-durable-ko-6:e1", evidenceMessageId: "succ-b101-6-m1", evidenceQuote: "통계는 대학원에서 전공해서 어느 정도 압니다." },
    { key: "succ-durable-ko-6:e2", evidenceMessageId: "succ-b101-6-m1", evidenceQuote: "기초 설명은 건너뛰고 바로 모델 선택 얘기로 가주세요." },
    { key: "succ-durable-ko-7:e1", evidenceMessageId: "succ-b101-7-m1", evidenceQuote: "최종 목표는 변호사가 되는 거예요." },
    { key: "succ-durable-ko-8:e1", evidenceMessageId: "succ-b101-8-m1", evidenceQuote: "쌍둥이 아들 둘 키우고 있어요." },
    { key: "succ-durable-ko-9:e1", evidenceMessageId: "succ-b101-9-m1", evidenceQuote: "코드 예시 줄 때 들여쓰기는 탭으로 해주세요." },
    { key: "succ-durable-ko-10:e1", evidenceMessageId: "succ-b101-10-m1", evidenceQuote: "비행기 예약할 때는 늘 창가 자리로 잡아요." },
    { key: "succ-durable-ko-11:e1", evidenceMessageId: "succ-b101-11-m1", evidenceQuote: "고민 끝에 postgres 쓰기로 정했습니다." },
    { key: "succ-durable-ko-13:e1", evidenceMessageId: "succ-b101-13-m1", evidenceQuote: "영어로 물어봐도 답은 한국어로 주세요." },
    { key: "succ-durable-ko-14:e1", evidenceMessageId: "succ-b101-14-m1", evidenceQuote: "세무사로 일한 지 12년 됐습니다." },
    { key: "succ-durable-ko-17:e1", evidenceMessageId: "succ-b101-17-m1", evidenceQuote: "비교할 게 여러 개면 표로 정리해 주는 게 제일 편해요." },
    { key: "succ-durable-ko-18:e1", evidenceMessageId: "succ-b101-18-m1", evidenceQuote: "1986년생이에요." },
    { key: "succ-durable-ko-19:e1", evidenceMessageId: "succ-b101-19-m1", evidenceQuote: "지금 기후 변화 관련 논문을 쓰고 있는데 자료 정리가 안 되네요." },
    { key: "succ-durable-ko-22:e1", evidenceMessageId: "succ-b101-22-m1", evidenceQuote: "고민하다가 매매 말고 전세로 가기로 결정했어요." },
    { key: "succ-durable-ko-24:e1", evidenceMessageId: "succ-b101-24-m1", evidenceQuote: "언젠가는 귀농할 생각이에요." },
    {
        key: "succ-durable-ko-25:e1",
        evidenceMessageId: "succ-b101-25-m1",
        evidenceQuote: "전화 통화는 싫어해서 되도록 문자나 메일로 처리해요.",
        sentenceChoice: true,
    },
    { key: "succ-durable-en-1:e1", evidenceMessageId: "succ-b102-1-m1", evidenceQuote: "I'm a paramedic, twelve-hour shifts, mostly nights this quarter." },
    { key: "succ-durable-en-1:e2", evidenceMessageId: "succ-b102-1-m1", evidenceQuote: "I'm a paramedic, twelve-hour shifts, mostly nights this quarter." },
    { key: "succ-durable-en-2:e1", evidenceMessageId: "succ-b102-2-m1", evidenceQuote: "I've been a high school chemistry teacher for eleven years." },
    { key: "succ-durable-en-4:e1", evidenceMessageId: "succ-b102-4-m1", evidenceQuote: "I'm based in Lisbon, if that changes any of your suggestions." },
    { key: "succ-durable-en-5:e1", evidenceMessageId: "succ-b102-5-m1", evidenceQuote: "I was born in 1974, for whatever that's worth here." },
    { key: "succ-durable-en-6:e1", evidenceMessageId: "succ-b102-6-m1", evidenceQuote: "I'd much rather see examples first and the theory afterwards." },
    { key: "succ-durable-en-9:e1", evidenceMessageId: "succ-b102-9-m1", evidenceQuote: "my budget is 2000 dollars and thats a hard limit, i cant go over it even a little" },
    { key: "succ-durable-en-11:e1", evidenceMessageId: "succ-b102-11-m1", evidenceQuote: "I've practised tax law for fifteen years." },
    { key: "succ-durable-en-11:e2", evidenceMessageId: "succ-b102-11-m1", evidenceQuote: "You can skip the introductions and go straight to the edge cases." },
    { key: "succ-durable-en-12:e1", evidenceMessageId: "succ-b102-12-m1", evidenceQuote: "I'm a complete beginner with spreadsheets." },
    { key: "succ-durable-en-13:e1", evidenceMessageId: "succ-b102-13-m1", evidenceQuote: "The goal is a marathon." },
    { key: "succ-durable-en-14:e1", evidenceMessageId: "succ-b102-14-m1", evidenceQuote: "I want to retire at 55." },
    { key: "succ-durable-en-15:e1", evidenceMessageId: "succ-b102-15-m1", evidenceQuote: "I'm restoring a 1968 camper van." },
    { key: "succ-durable-en-16:e1", evidenceMessageId: "succ-b102-16-m1", evidenceQuote: "I'm putting together a cookbook of my grandmother's recipes." },
    { key: "succ-durable-en-17:e1", evidenceMessageId: "succ-b102-17-m1", evidenceQuote: "We've decided on kubernetes." },
    { key: "succ-durable-en-18:e1", evidenceMessageId: "succ-b102-18-m1", evidenceQuote: "After a lot of back and forth we decided to homeschool our daughter starting this autumn." },
    { key: "succ-durable-en-24:e1", evidenceMessageId: "succ-b102-24-m1", evidenceQuote: "Write your answers in spanish even when I ask in English." },
    { key: "succ-durable-en-25:e1", evidenceMessageId: "succ-b102-25-m1", evidenceQuote: "Every python example you give me should have type hints." },
    { key: "succ-durable-ko-26:e1", evidenceMessageId: "succ-b103-1-m1", evidenceQuote: "대전에서 나고 자랐고 지금도 거기 삽니다." },
    { key: "succ-durable-ko-27:e1", evidenceMessageId: "succ-b103-2-m1", evidenceQuote: "93년생입니다." },
    { key: "succ-durable-ko-30:e1", evidenceMessageId: "succ-b103-5-m1", evidenceQuote: "회의는 아침에 잡는 걸 선호합니다." },
    { key: "succ-durable-ko-31:e1", evidenceMessageId: "succ-b103-6-m1", evidenceQuote: "삼십 분 안쪽 거리는 무조건 걸어 다닙니다." },
    { key: "succ-durable-ko-32:e1", evidenceMessageId: "succ-b103-7-m1", evidenceQuote: "웬만한 물건은 중고로 삽니다." },
    { key: "succ-durable-ko-33:e1", evidenceMessageId: "succ-b103-8-m1", evidenceQuote: "매운 걸 워낙 좋아해서 맵찔이용 메뉴는 안 알려주셔도 됩니다 🌶️" },
    { key: "succ-durable-ko-34:e1", evidenceMessageId: "succ-b103-9-m1", evidenceQuote: "물리치료사로 일한 지 7년 됐습니다." },
    { key: "succ-durable-ko-35:e1", evidenceMessageId: "succ-b103-10-m1", evidenceQuote: "저는 항해사입니다." },
    { key: "succ-durable-ko-35:e2", evidenceMessageId: "succ-b103-10-m1", evidenceQuote: "육 개월씩 배를 타고 나가 있어서 연락이 뜸해요." },
    { key: "succ-durable-ko-36:e1", evidenceMessageId: "succ-b103-11-m1", evidenceQuote: "제빵 일을 합니다." },
    { key: "succ-durable-ko-36:e2", evidenceMessageId: "succ-b103-11-m1", evidenceQuote: "새벽 세 시에 시작해서 오후 두 시에 끝나요." },
    { key: "succ-durable-ko-37:e1", evidenceMessageId: "succ-b103-12-m1", evidenceQuote: "구청에서 공무원으로 일하고 있어요." },
    { key: "succ-durable-ko-38:e1", evidenceMessageId: "succ-b103-13-m1", evidenceQuote: "엑셀은 피벗이랑 함수까지 능숙하게 씁니다." },
    { key: "succ-durable-ko-38:e2", evidenceMessageId: "succ-b103-13-m1", evidenceQuote: "기초 설명은 빼주세요." },
    { key: "succ-durable-ko-39:e1", evidenceMessageId: "succ-b103-14-m1", evidenceQuote: "클래식 기타를 십오 년 쳤습니다." },
    { key: "succ-durable-ko-39:e2", evidenceMessageId: "succ-b103-14-m1", evidenceQuote: "코드 이름 정도는 그냥 말씀하셔도 됩니다." },
    { key: "succ-durable-ko-40:e1", evidenceMessageId: "succ-b103-15-m1", evidenceQuote: "주식은 이번에 처음 시작합니다." },
    { key: "succ-durable-ko-41:e1", evidenceMessageId: "succ-b103-16-m1", evidenceQuote: "목공은 취미로 오래 했어요." },
    { key: "succ-durable-ko-42:e1", evidenceMessageId: "succ-b103-17-m1", evidenceQuote: "언젠가 작은 책방을 여는 게 목표입니다." },
    { key: "succ-durable-ko-43:e1", evidenceMessageId: "succ-b103-18-m1", evidenceQuote: "최종적으로는 박사까지 갈 생각입니다." },
    { key: "succ-durable-ko-44:e1", evidenceMessageId: "succ-b103-19-m1", evidenceQuote: "오 년 안에 제주로 완전히 이주하려고 준비 중입니다." },
    { key: "succ-durable-ko-45:e1", evidenceMessageId: "succ-b103-20-m1", evidenceQuote: "쇼팽 발라드 1번을 끝까지 치는 게 목표예요." },
    { key: "succ-durable-ko-46:e1", evidenceMessageId: "succ-b103-21-m1", evidenceQuote: "유튜브 채널을 혼자 굴리고 있어요." },
    { key: "succ-durable-ko-48:e1", evidenceMessageId: "succ-b103-23-m1", evidenceQuote: "스페인어 소설 하나를 번역하고 있습니다." },
    { key: "succ-durable-ko-49:e1", evidenceMessageId: "succ-b103-24-m1", evidenceQuote: "보드게임을 하나 만들고 있어요." },
    { key: "succ-durable-ko-53:e1", evidenceMessageId: "succ-b104-3-m1", evidenceQuote: "무릎이 안 좋아서 계단이나 등산은 무리예요." },
    { key: "succ-durable-ko-54:e1", evidenceMessageId: "succ-b104-4-m1", evidenceQuote: "저염식을 해야 합니다." },
    { key: "succ-durable-ko-55:e1", evidenceMessageId: "succ-b104-5-m1", evidenceQuote: "고민 끝에 이직하기로 결정했습니다." },
    { key: "succ-durable-ko-56:e1", evidenceMessageId: "succ-b104-6-m1", evidenceQuote: "올해 안에 자취하기로 정했어요." },
    { key: "succ-durable-ko-57:e1", evidenceMessageId: "succ-b104-7-m1", evidenceQuote: "대학원은 안 가기로 했습니다." },
    { key: "succ-durable-ko-58:e1", evidenceMessageId: "succ-b104-8-m1", evidenceQuote: "차는 경차로 가기로 했어요." },
    { key: "succ-durable-ko-60:e1", evidenceMessageId: "succ-b104-10-m1", evidenceQuote: "남동생이 한 명 있고 같은 회사에 다닙니다." },
    { key: "succ-durable-ko-63:e1", evidenceMessageId: "succ-b104-13-m1", evidenceQuote: "새벽에 일하고 낮에 잡니다." },
    { key: "succ-durable-ko-64:e1", evidenceMessageId: "succ-b104-14-m1", evidenceQuote: "토요일 오전은 늘 봉사 활동이 있습니다." },
    { key: "succ-durable-ko-65:e1", evidenceMessageId: "succ-b104-15-m1", evidenceQuote: "격주로 지방 출장을 갑니다." },
    { key: "succ-durable-ko-66:e1", evidenceMessageId: "succ-b104-16-m1", evidenceQuote: "비유를 들어서 설명해 주시면 훨씬 잘 들어와요." },
    { key: "succ-durable-ko-67:e1", evidenceMessageId: "succ-b104-17-m1", evidenceQuote: "애매하면 그냥 넘기지 말고 질문을 먼저 해주세요." },
    { key: "succ-durable-ko-69:e1", evidenceMessageId: "succ-b104-19-m1", evidenceQuote: "저는 자세히 받는 걸 좋아합니다." },
    { key: "succ-durable-ko-70:e1", evidenceMessageId: "succ-b104-20-m1", evidenceQuote: "설명은 단계별로 나눠서 주세요." },
    { key: "succ-durable-ko-71:e1", evidenceMessageId: "succ-b104-21-m1", evidenceQuote: "줄글보다 목록 형태가 읽기 편해요." },
    {
        key: "succ-durable-ko-72:e1",
        evidenceMessageId: "succ-b104-22-m1",
        evidenceQuote: "한국어로 물어봐도 답은 영어로 주세요.",
        sentenceChoice: true,
    },
    { key: "succ-durable-ko-73:e1", evidenceMessageId: "succ-b104-23-m1", evidenceQuote: "방법만 알려주지 마시고 원리까지 같이 설명해 주세요." },
    { key: "succ-durable-ko-74:e1", evidenceMessageId: "succ-b104-24-m1", evidenceQuote: "사실 관계를 말할 때는 출처를 같이 달아 주세요." },
    { key: "succ-durable-ko-75:e1", evidenceMessageId: "succ-b104-25-m1", evidenceQuote: "코드 예시에는 주석을 촘촘히 달아 주세요." },
    { key: "succ-durable-en-27:e1", evidenceMessageId: "succ-b105-2-m1", evidenceQuote: "Born in 1988, if that matters for any of the age-banded stuff." },
    { key: "succ-durable-en-31:e1", evidenceMessageId: "succ-b105-6-m1", evidenceQuote: "For anything under six hours I'd rather take the train than fly." },
    { key: "succ-durable-en-32:e1", evidenceMessageId: "succ-b105-7-m1", evidenceQuote: "I buy almost everything secondhand." },
    { key: "succ-durable-en-33:e1", evidenceMessageId: "succ-b105-8-m1", evidenceQuote: "I read on paper." },
    { key: "succ-durable-en-34:e1", evidenceMessageId: "succ-b105-9-m1", evidenceQuote: "I'm a midwife." },
    { key: "succ-durable-en-34:e2", evidenceMessageId: "succ-b105-9-m1", evidenceQuote: "Twelve-hour shifts, mostly nights." },
    { key: "succ-durable-en-35:e1", evidenceMessageId: "succ-b105-10-m1", evidenceQuote: "I work as an archivist at a county records office." },
    { key: "succ-durable-en-36:e1", evidenceMessageId: "succ-b105-11-m1", evidenceQuote: "I'm a self-employed electrician, so my invoicing questions are about my own books." },
    { key: "succ-durable-en-37:e1", evidenceMessageId: "succ-b105-12-m1", evidenceQuote: "I'm a freelance translator working on legal documents, about six clients." },
    { key: "succ-durable-en-39:e1", evidenceMessageId: "succ-b105-14-m1", evidenceQuote: "I've been sailing since I was a kid." },
    { key: "succ-durable-en-40:e1", evidenceMessageId: "succ-b105-15-m1", evidenceQuote: "I'm completely new to gardening." },
    { key: "succ-durable-en-42:e1", evidenceMessageId: "succ-b105-17-m1", evidenceQuote: "The long-term plan is a year-long sabbatical to write." },
    { key: "succ-durable-en-43:e1", evidenceMessageId: "succ-b105-18-m1", evidenceQuote: "I'm working toward citizenship here." },
    { key: "succ-durable-en-44:e1", evidenceMessageId: "succ-b105-19-m1", evidenceQuote: "Everything I'm doing financially is aimed at being debt free." },
    { key: "succ-durable-en-45:e1", evidenceMessageId: "succ-b105-20-m1", evidenceQuote: "Eventually I want to teach at a community college." },
    { key: "succ-durable-en-46:e1", evidenceMessageId: "succ-b105-21-m1", evidenceQuote: "I'm building a greenhouse in the back garden." },
    { key: "succ-durable-en-47:e1", evidenceMessageId: "succ-b105-22-m1", evidenceQuote: "I run a small podcast about local history." },
    { key: "succ-durable-en-48:e1", evidenceMessageId: "succ-b105-23-m1", evidenceQuote: "My thesis is on coastal erosion." },
    { key: "succ-durable-en-49:e1", evidenceMessageId: "succ-b105-24-m1", evidenceQuote: "I'm restoring a 1970s motorbike in the garage." },
    { key: "succ-durable-en-50:e1", evidenceMessageId: "succ-b105-25-m1", evidenceQuote: "We settled on Postgres for the new service." },
    { key: "succ-durable-en-51:e1", evidenceMessageId: "succ-b106-1-m1", evidenceQuote: "We decided to keep renting rather than buy." },
    { key: "succ-durable-en-53:e1", evidenceMessageId: "succ-b106-3-m1", evidenceQuote: "After the last mess we decided to consolidate to one supplier." },
    { key: "succ-durable-en-54:e1", evidenceMessageId: "succ-b106-4-m1", evidenceQuote: "My daughter is coeliac, so anything I cook at home has to be gluten free." },
    { key: "succ-durable-en-55:e1", evidenceMessageId: "succ-b106-5-m1", evidenceQuote: "My mother lives in Japan and I visit twice a year." },
    { key: "succ-durable-en-59:e1", evidenceMessageId: "succ-b106-9-m1", evidenceQuote: "Severe shellfish allergy here." },
    { key: "succ-durable-en-60:e1", evidenceMessageId: "succ-b106-10-m1", evidenceQuote: "I'm on Windows only." },
    { key: "succ-durable-en-64:e1", evidenceMessageId: "succ-b106-14-m1", evidenceQuote: "We close the books at the end of each quarter and that week is always chaos." },
    { key: "succ-durable-en-66:e1", evidenceMessageId: "succ-b106-16-m1", evidenceQuote: "Please drop the disclaimers." },
    { key: "succ-durable-en-67:e1", evidenceMessageId: "succ-b106-17-m1", evidenceQuote: "If my question is ambiguous, ask me one clarifying question before answering." },
    { key: "succ-durable-en-68:e1", evidenceMessageId: "succ-b106-18-m1", evidenceQuote: "Keep it formal, please." },
    { key: "succ-durable-en-69:e1", evidenceMessageId: "succ-b106-19-m1", evidenceQuote: "Short answers." },
    { key: "succ-durable-en-70:e1", evidenceMessageId: "succ-b106-20-m1", evidenceQuote: "Give me the conclusion first and the reasoning after it." },
    { key: "succ-durable-en-71:e1", evidenceMessageId: "succ-b106-21-m1", evidenceQuote: "Use tables when you're comparing things." },
    { key: "succ-durable-en-72:e1", evidenceMessageId: "succ-b106-22-m1", evidenceQuote: "Answer me in German even when I write in English." },
    { key: "succ-durable-en-74:e1", evidenceMessageId: "succ-b106-24-m1", evidenceQuote: "When you cite something, point me at primary sources rather than summaries." },
    { key: "succ-durable-en-75:e1", evidenceMessageId: "succ-b106-25-m1", evidenceQuote: "Any code example you give me should come with a test." },
    { key: "succ-durable-ko-77:e1", evidenceMessageId: "succ-b107-2-m1", evidenceQuote: "78년생입니다." },
    { key: "succ-durable-ko-80:e1", evidenceMessageId: "succ-b107-5-m1", evidenceQuote: "커피는 안 마시고 녹차만 마십니다." },
    { key: "succ-durable-ko-81:e1", evidenceMessageId: "succ-b107-6-m1", evidenceQuote: "이메일보다 메신저가 훨씬 편합니다." },
    { key: "succ-durable-ko-82:e1", evidenceMessageId: "succ-b107-7-m1", evidenceQuote: "엘리베이터 두고 계단으로 다닙니다." },
    { key: "succ-durable-ko-85:e1", evidenceMessageId: "succ-b107-10-m1", evidenceQuote: "동네 동물병원에서 수의사로 일합니다." },
    { key: "succ-durable-ko-86:e1", evidenceMessageId: "succ-b107-11-m1", evidenceQuote: "미용사로 일한 지 십이 년째입니다." },
    { key: "succ-durable-ko-87:e1", evidenceMessageId: "succ-b107-12-m1", evidenceQuote: "택배 일을 합니다." },
    { key: "succ-durable-ko-88:e1", evidenceMessageId: "succ-b107-13-m1", evidenceQuote: "사진은 필름 현상까지 직접 합니다." },
    { key: "succ-durable-ko-88:e2", evidenceMessageId: "succ-b107-13-m1", evidenceQuote: "노출이나 현상 용어는 설명 안 하셔도 됩니다." },
    { key: "succ-durable-ko-89:e1", evidenceMessageId: "succ-b107-14-m1", evidenceQuote: "독일어는 업무로 쓸 만큼 합니다." },
    { key: "succ-durable-ko-90:e1", evidenceMessageId: "succ-b107-15-m1", evidenceQuote: "회계는 이번에 처음 봅니다." },
    { key: "succ-durable-ko-91:e1", evidenceMessageId: "succ-b107-16-m1", evidenceQuote: "암벽 등반을 오래 했습니다." },
    { key: "succ-durable-ko-91:e2", evidenceMessageId: "succ-b107-16-m1", evidenceQuote: "그레이드 얘기는 그냥 하셔도 알아들어요." },
    { key: "succ-durable-ko-92:e1", evidenceMessageId: "succ-b107-17-m1", evidenceQuote: "산티아고 순례길을 완주하는 게 오래된 목표입니다." },
    { key: "succ-durable-ko-93:e1", evidenceMessageId: "succ-b107-18-m1", evidenceQuote: "결국은 작은 카페를 차리는 게 목표예요." },
    { key: "succ-durable-ko-94:e1", evidenceMessageId: "succ-b107-19-m1", evidenceQuote: "공인중개사 자격증을 따는 게 몇 년째 목표입니다." },
    { key: "succ-durable-ko-95:e1", evidenceMessageId: "succ-b107-20-m1", evidenceQuote: "언젠가 목조주택을 직접 지어서 살고 싶습니다." },
    { key: "succ-durable-ko-96:e1", evidenceMessageId: "succ-b107-21-m1", evidenceQuote: "집안 족보를 디지털로 정리하고 있습니다." },
    { key: "succ-durable-ko-97:e1", evidenceMessageId: "succ-b107-22-m1", evidenceQuote: "습관 기록용 웹앱을 혼자 만들고 있어요." },
    { key: "succ-durable-ko-98:e1", evidenceMessageId: "succ-b107-23-m1", evidenceQuote: "자전거 국토종주를 준비하고 있습니다." },
    { key: "succ-durable-ko-100:e1", evidenceMessageId: "succ-b107-25-m1", evidenceQuote: "재택으로 계속 가기로 회사랑 얘기 끝냈습니다." },
    { key: "succ-durable-ko-101:e1", evidenceMessageId: "succ-b108-1-m1", evidenceQuote: "종신보험은 해지하기로 결정했습니다." },
    { key: "succ-durable-ko-102:e1", evidenceMessageId: "succ-b108-2-m1", evidenceQuote: "아이는 학원 안 보내기로 정했습니다." },
    { key: "succ-durable-ko-103:e1", evidenceMessageId: "succ-b108-3-m1", evidenceQuote: "개명하기로 마음먹고 서류까지 넣었습니다." },
    { key: "succ-durable-ko-104:e1", evidenceMessageId: "succ-b108-4-m1", evidenceQuote: "아버지가 당뇨가 있으셔서 같이 먹는 음식은 다 그걸 고려해야 합니다." },
    { key: "succ-durable-ko-108:e1", evidenceMessageId: "succ-b108-8-m1", evidenceQuote: "견과류 알레르기가 심합니다." },
    { key: "succ-durable-ko-110:e1", evidenceMessageId: "succ-b108-10-m1", evidenceQuote: "손목 터널 증후군이 있어서 오래 타이핑하는 방법은 피해야 합니다." },
    { key: "succ-durable-ko-114:e1", evidenceMessageId: "succ-b108-14-m1", evidenceQuote: "수요일 오후는 매주 병원에 갑니다." },
    { key: "succ-durable-ko-115:e1", evidenceMessageId: "succ-b108-15-m1", evidenceQuote: "명절마다 지방에 내려가 있어서 그때는 연락이 잘 안 됩니다." },
    { key: "succ-durable-ko-117:e1", evidenceMessageId: "succ-b108-17-m1", evidenceQuote: "제 생각이 틀렸다고 보이면 반대 의견을 그대로 말해 주세요." },
    { key: "succ-durable-ko-119:e1", evidenceMessageId: "succ-b108-19-m1", evidenceQuote: "답은 세 문장 안쪽으로 부탁드립니다." },
    { key: "succ-durable-ko-120:e1", evidenceMessageId: "succ-b108-20-m1", evidenceQuote: "긴 답변에는 소제목을 붙여 주세요." },
    { key: "succ-durable-ko-121:e1", evidenceMessageId: "succ-b108-21-m1", evidenceQuote: "핵심 문장은 굵게 표시해 주세요." },
    { key: "succ-durable-ko-122:e1", evidenceMessageId: "succ-b108-22-m1", evidenceQuote: "중국어 공부 중이라 답변은 중국어로 주시면 좋겠습니다." },
    { key: "succ-durable-ko-123:e1", evidenceMessageId: "succ-b108-23-m1", evidenceQuote: "이론까지 파고들지 마시고 실무에서 쓸 만큼만 설명해 주세요." },
    { key: "succ-durable-ko-124:e1", evidenceMessageId: "succ-b108-24-m1", evidenceQuote: "블로그 말고 공식 문서를 인용해 주세요." },
    { key: "succ-durable-ko-125:e1", evidenceMessageId: "succ-b108-25-m1", evidenceQuote: "코드 예시에서 변수명은 줄이지 말고 온전한 영어 단어로 써 주세요." },
    { key: "succ-durable-en-77:e1", evidenceMessageId: "succ-b109-2-m1", evidenceQuote: "I was born in 1995 if any of this is age dependent." },
    { key: "succ-durable-en-80:e1", evidenceMessageId: "succ-b109-5-m1", evidenceQuote: "I get through books as audiobooks." },
    { key: "succ-durable-en-81:e1", evidenceMessageId: "succ-b109-6-m1", evidenceQuote: "I'd rather have a walking meeting than sit in a room for an hour." },
    { key: "succ-durable-en-82:e1", evidenceMessageId: "succ-b109-7-m1", evidenceQuote: "It's tea, all day." },
    { key: "succ-durable-en-84:e1", evidenceMessageId: "succ-b109-9-m1", evidenceQuote: "I'm a veterinary nurse at a small animal practice." },
    { key: "succ-durable-en-85:e1", evidenceMessageId: "succ-b109-10-m1", evidenceQuote: "I've been a locksmith for eighteen years, mostly emergency call-outs." },
    { key: "succ-durable-en-86:e1", evidenceMessageId: "succ-b109-11-m1", evidenceQuote: "I work in air traffic control." },
    { key: "succ-durable-en-86:e2", evidenceMessageId: "succ-b109-11-m1", evidenceQuote: "The shift pattern is brutal and it rules everything else." },
    { key: "succ-durable-en-87:e1", evidenceMessageId: "succ-b109-12-m1", evidenceQuote: "I'm a copy editor." },
    { key: "succ-durable-en-89:e1", evidenceMessageId: "succ-b109-14-m1", evidenceQuote: "I've been knitting since I was six." },
    { key: "succ-durable-en-92:e1", evidenceMessageId: "succ-b109-17-m1", evidenceQuote: "The plan, eventually, is a smallholding." },
    { key: "succ-durable-en-93:e1", evidenceMessageId: "succ-b109-18-m1", evidenceQuote: "I want to end up doing a PhD." },
    { key: "succ-durable-en-94:e1", evidenceMessageId: "succ-b109-19-m1", evidenceQuote: "Crossing the Atlantic under sail is the thing I'm building toward." },
    { key: "succ-durable-en-95:e1", evidenceMessageId: "succ-b109-20-m1", evidenceQuote: "I want to open a small gallery for local artists someday." },
    { key: "succ-durable-en-96:e1", evidenceMessageId: "succ-b109-21-m1", evidenceQuote: "I'm designing a board game." },
    { key: "succ-durable-en-97:e1", evidenceMessageId: "succ-b109-22-m1", evidenceQuote: "I'm writing a memoir about my years at sea." },
    { key: "succ-durable-en-98:e1", evidenceMessageId: "succ-b109-23-m1", evidenceQuote: "I'm building a treehouse for my nephews." },
    { key: "succ-durable-en-99:e1", evidenceMessageId: "succ-b109-24-m1", evidenceQuote: "I run a fortnightly newsletter about urban wildlife." },
    { key: "succ-durable-en-100:e1", evidenceMessageId: "succ-b109-25-m1", evidenceQuote: "I decided to stay freelance rather than take a staff job." },
    { key: "succ-durable-en-102:e1", evidenceMessageId: "succ-b110-2-m1", evidenceQuote: "We decided to outsource payroll rather than keep it in house." },
    { key: "succ-durable-en-103:e1", evidenceMessageId: "succ-b110-3-m1", evidenceQuote: "We dropped the extended insurance after doing the maths." },
    { key: "succ-durable-en-104:e1", evidenceMessageId: "succ-b110-4-m1", evidenceQuote: "My son is autistic, and routine changes are genuinely hard for him." },
    { key: "succ-durable-en-107:e1", evidenceMessageId: "succ-b110-7-m1", evidenceQuote: "My grandmother lives with us and I'm her main carer." },
    { key: "succ-durable-en-114:e1", evidenceMessageId: "succ-b110-14-m1", evidenceQuote: "Month end is always a scramble for us — invoicing, reporting, all of it at once." },
    { key: "succ-durable-en-115:e1", evidenceMessageId: "succ-b110-15-m1", evidenceQuote: "During term time my evenings disappear." },
    { key: "succ-durable-en-117:e1", evidenceMessageId: "succ-b110-17-m1", evidenceQuote: "If you think I'm wrong, push back." },
    { key: "succ-durable-en-118:e1", evidenceMessageId: "succ-b110-18-m1", evidenceQuote: "Keep it casual." },
    { key: "succ-durable-en-119:e1", evidenceMessageId: "succ-b110-19-m1", evidenceQuote: "Cap answers at three sentences unless I ask for more." },
    { key: "succ-durable-en-120:e1", evidenceMessageId: "succ-b110-20-m1", evidenceQuote: "Use headings on anything long." },
    { key: "succ-durable-en-121:e1", evidenceMessageId: "succ-b110-21-m1", evidenceQuote: "Put the key sentence in bold so I can find it when I skim back." },
    { key: "succ-durable-en-123:e1", evidenceMessageId: "succ-b110-23-m1", evidenceQuote: "Skip the theory and keep it practical." },
    { key: "succ-durable-en-124:e1", evidenceMessageId: "succ-b110-24-m1", evidenceQuote: "Cite the official docs rather than a blog post." },
    { key: "succ-durable-en-125:e1", evidenceMessageId: "succ-b110-25-m1", evidenceQuote: "Write out full variable names in examples." },
    { key: "succ-durable-ko-131:e1", evidenceMessageId: "succ-b111-6-m1", evidenceQuote: "인천에 삽니다." },
    { key: "succ-durable-ko-132:e1", evidenceMessageId: "succ-b111-7-m1", evidenceQuote: "65년생입니다." },
    { key: "succ-durable-ko-135:e1", evidenceMessageId: "succ-b111-10-m1", evidenceQuote: "뉴스는 종이 신문으로 봅니다." },
    { key: "succ-durable-ko-136:e1", evidenceMessageId: "succ-b111-11-m1", evidenceQuote: "한국어 영상도 자막을 켜고 봅니다." },
    { key: "succ-durable-ko-137:e1", evidenceMessageId: "succ-b111-12-m1", evidenceQuote: "혼밥이 편합니다." },
    { key: "succ-durable-ko-138:e1", evidenceMessageId: "succ-b111-13-m1", evidenceQuote: "가능하면 현금으로 냅니다." },
    { key: "succ-durable-ko-139:e1", evidenceMessageId: "succ-b111-14-m1", evidenceQuote: "치과위생사로 일합니다." },
    { key: "succ-durable-ko-139:e2", evidenceMessageId: "succ-b111-14-m1", evidenceQuote: "토요일도 진료가 있어요." },
    { key: "succ-durable-ko-141:e1", evidenceMessageId: "succ-b111-16-m1", evidenceQuote: "학교 급식실에서 조리사로 일합니다." },
    { key: "succ-durable-ko-142:e1", evidenceMessageId: "succ-b111-17-m1", evidenceQuote: "도배 일을 합니다." },
    { key: "succ-durable-ko-143:e1", evidenceMessageId: "succ-b111-18-m1", evidenceQuote: "서예를 이십 년 했습니다." },
    { key: "succ-durable-ko-143:e2", evidenceMessageId: "succ-b111-18-m1", evidenceQuote: "서체 이름은 그냥 쓰셔도 됩니다." },
    { key: "succ-durable-ko-144:e1", evidenceMessageId: "succ-b111-19-m1", evidenceQuote: "자동차 정비는 제 전공이라 부품 이름은 설명 안 하셔도 됩니다." },
    { key: "succ-durable-ko-144:e2", evidenceMessageId: "succ-b111-19-m1", evidenceQuote: "자동차 정비는 제 전공이라 부품 이름은 설명 안 하셔도 됩니다." },
    { key: "succ-durable-ko-146:e1", evidenceMessageId: "succ-b111-21-m1", evidenceQuote: "응급처치 강사 자격이 있습니다." },
    { key: "succ-durable-ko-146:e2", evidenceMessageId: "succ-b111-21-m1", evidenceQuote: "의학 용어는 그대로 쓰셔도 됩니다." },
    { key: "succ-durable-ko-147:e1", evidenceMessageId: "succ-b111-22-m1", evidenceQuote: "시집을 한 권 내는 게 오래된 목표입니다." },
    { key: "succ-durable-ko-148:e1", evidenceMessageId: "succ-b111-23-m1", evidenceQuote: "언젠가 세계일주를 하려고 지금 저축하고 있습니다." },
    { key: "succ-durable-ko-149:e1", evidenceMessageId: "succ-b111-24-m1", evidenceQuote: "사회복지사로 직업을 바꾸는 게 목표입니다." },
    { key: "succ-durable-ko-150:e1", evidenceMessageId: "succ-b111-25-m1", evidenceQuote: "동네 골목길 지도를 직접 만들고 있습니다." },
    { key: "succ-durable-ko-151:e1", evidenceMessageId: "succ-b111-26-m1", evidenceQuote: "밴드에서 앨범을 녹음하고 있습니다." },
    { key: "succ-durable-ko-152:e1", evidenceMessageId: "succ-b111-27-m1", evidenceQuote: "시골에 있는 한옥을 고치고 있습니다." },
    { key: "succ-durable-ko-154:e1", evidenceMessageId: "succ-b111-29-m1", evidenceQuote: "투자보다 대출 상환을 먼저 하기로 정했습니다." },
    { key: "succ-durable-ko-155:e1", evidenceMessageId: "succ-b111-30-m1", evidenceQuote: "부업은 다 정리하기로 했습니다." },
    { key: "succ-durable-ko-160:e1", evidenceMessageId: "succ-b111-35-m1", evidenceQuote: "토요일 오전은 매주 조기축구입니다." },
    { key: "succ-durable-ko-164:e1", evidenceMessageId: "succ-b111-39-m1", evidenceQuote: "유머는 넣지 말고 진지하게만 답해 주세요." },
    { key: "succ-durable-ko-165:e1", evidenceMessageId: "succ-b111-40-m1", evidenceQuote: "답은 한 문단으로 부탁드립니다." },
    { key: "succ-durable-ko-166:e1", evidenceMessageId: "succ-b111-41-m1", evidenceQuote: "긴 답변은 맨 앞에 요약을 붙여 주세요." },
    { key: "succ-durable-ko-167:e1", evidenceMessageId: "succ-b111-42-m1", evidenceQuote: "이모지는 쓰지 말아 주세요." },
    { key: "succ-durable-ko-168:e1", evidenceMessageId: "succ-b111-43-m1", evidenceQuote: "스페인어로 답해 주세요." },
    { key: "succ-durable-ko-169:e1", evidenceMessageId: "succ-b111-44-m1", evidenceQuote: "초등학생한테 설명하듯 풀어 주세요." },
    { key: "succ-durable-ko-170:e1", evidenceMessageId: "succ-b111-45-m1", evidenceQuote: "자료를 인용할 때 연도까지 적어 주세요." },
    { key: "succ-durable-ko-171:e1", evidenceMessageId: "succ-b111-46-m1", evidenceQuote: "코드 예시는 파일을 나누지 말고 한 파일로 주세요." },
    { key: "succ-durable-en-126:e1", evidenceMessageId: "succ-b112-1-m1", evidenceQuote: "I'm coeliac, so gluten is completely off the table for me." },
    { key: "succ-durable-en-127:e1", evidenceMessageId: "succ-b112-2-m1", evidenceQuote: "I react badly to fragrance, so scented products are out." },
    { key: "succ-durable-en-131:e1", evidenceMessageId: "succ-b112-6-m1", evidenceQuote: "I'm in Cardiff and have been for most of my adult life." },
    { key: "succ-durable-en-132:e1", evidenceMessageId: "succ-b112-7-m1", evidenceQuote: "Born in 1962, so retirement questions are live ones for me." },
    { key: "succ-durable-en-135:e1", evidenceMessageId: "succ-b112-10-m1", evidenceQuote: "I read a printed newspaper." },
    { key: "succ-durable-en-136:e1", evidenceMessageId: "succ-b112-11-m1", evidenceQuote: "I watch everything with subtitles on, even in my own language." },
    { key: "succ-durable-en-137:e1", evidenceMessageId: "succ-b112-12-m1", evidenceQuote: "I actually prefer eating alone." },
    { key: "succ-durable-en-138:e1", evidenceMessageId: "succ-b112-13-m1", evidenceQuote: "I pay in cash wherever I can." },
    { key: "succ-durable-en-139:e1", evidenceMessageId: "succ-b112-14-m1", evidenceQuote: "I'm a dental hygienist." },
    { key: "succ-durable-en-139:e2", evidenceMessageId: "succ-b112-14-m1", evidenceQuote: "We run Saturday clinics too." },
    { key: "succ-durable-en-140:e1", evidenceMessageId: "succ-b112-15-m1", evidenceQuote: "I run an apple orchard." },
    { key: "succ-durable-en-140:e2", evidenceMessageId: "succ-b112-15-m1", evidenceQuote: "During harvest I'm unavailable for anything else." },
    { key: "succ-durable-en-141:e1", evidenceMessageId: "succ-b112-16-m1", evidenceQuote: "I'm a school cook, so my day ends early but starts at six." },
    { key: "succ-durable-en-141:e2", evidenceMessageId: "succ-b112-16-m1", evidenceQuote: "I'm a school cook, so my day ends early but starts at six." },
    { key: "succ-durable-en-142:e1", evidenceMessageId: "succ-b112-17-m1", evidenceQuote: "I'm a decorator." },
    { key: "succ-durable-en-143:e1", evidenceMessageId: "succ-b112-18-m1", evidenceQuote: "I've done calligraphy for twenty years — you can use the proper script names." },
    { key: "succ-durable-en-143:e2", evidenceMessageId: "succ-b112-18-m1", evidenceQuote: "I've done calligraphy for twenty years — you can use the proper script names." },
    { key: "succ-durable-en-147:e1", evidenceMessageId: "succ-b112-22-m1", evidenceQuote: "Publishing a poetry collection is the long-term aim." },
    { key: "succ-durable-en-148:e1", evidenceMessageId: "succ-b112-23-m1", evidenceQuote: "The plan is to move abroad eventually." },
    { key: "succ-durable-en-149:e1", evidenceMessageId: "succ-b112-24-m1", evidenceQuote: "I want to retrain into social work." },
    { key: "succ-durable-en-150:e1", evidenceMessageId: "succ-b112-25-m1", evidenceQuote: "I'm mapping the local footpaths, walking and recording them one by one." },
    { key: "succ-durable-en-151:e1", evidenceMessageId: "succ-b112-26-m1", evidenceQuote: "My band is recording an album." },
    { key: "succ-durable-en-152:e1", evidenceMessageId: "succ-b112-27-m1", evidenceQuote: "I'm converting an old barn." },
    { key: "succ-durable-en-154:e1", evidenceMessageId: "succ-b112-29-m1", evidenceQuote: "We decided to overpay the mortgage rather than invest." },
    { key: "succ-durable-en-155:e1", evidenceMessageId: "succ-b112-30-m1", evidenceQuote: "I wound down the side business deliberately." },
    { key: "succ-durable-en-157:e1", evidenceMessageId: "succ-b112-32-m1", evidenceQuote: "My daughter is at university, so the house is quieter than it used to be." },
    { key: "succ-durable-en-158:e1", evidenceMessageId: "succ-b112-33-m1", evidenceQuote: "My father-in-law lives with us, and household decisions go through him too." },
    { key: "succ-durable-en-159:e1", evidenceMessageId: "succ-b112-34-m1", evidenceQuote: "Every October is appraisal season and it swallows the whole month." },
    { key: "succ-durable-en-161:e1", evidenceMessageId: "succ-b112-36-m1", evidenceQuote: "Summer is peak season for us, so those three months I barely get a day off." },
    { key: "succ-durable-en-163:e1", evidenceMessageId: "succ-b112-38-m1", evidenceQuote: "Keep the jargon but put a short gloss in brackets." },
    { key: "succ-durable-en-165:e1", evidenceMessageId: "succ-b112-40-m1", evidenceQuote: "One paragraph per answer." },
    { key: "succ-durable-en-169:e1", evidenceMessageId: "succ-b112-44-m1", evidenceQuote: "Explain things as you would to a twelve year old." },
    { key: "succ-durable-en-170:e1", evidenceMessageId: "succ-b112-45-m1", evidenceQuote: "When you cite something, give me the publication year." },
    { key: "succ-durable-en-171:e1", evidenceMessageId: "succ-b112-46-m1", evidenceQuote: "Give code examples as a single file rather than split across modules." },
    { key: "succ-durable-ko-174:e1", evidenceMessageId: "succ-b113-3-m1", evidenceQuote: "노트북이 십 년 된 거라 무거운 프로그램은 아예 안 돌아갑니다." },
    { key: "succ-durable-ko-176:e1", evidenceMessageId: "succ-b113-5-m1", evidenceQuote: "2001년생입니다." },
    { key: "succ-durable-ko-177:e1", evidenceMessageId: "succ-b113-6-m1", evidenceQuote: "지하철보다 버스를 탑니다." },
    { key: "succ-durable-ko-178:e1", evidenceMessageId: "succ-b113-7-m1", evidenceQuote: "메모는 손글씨로 합니다." },
    { key: "succ-durable-ko-179:e1", evidenceMessageId: "succ-b113-8-m1", evidenceQuote: "항공 승무원입니다." },
    { key: "succ-durable-ko-179:e2", evidenceMessageId: "succ-b113-8-m1", evidenceQuote: "한 달에 열흘은 해외에 있어요." },
    { key: "succ-durable-ko-180:e1", evidenceMessageId: "succ-b113-9-m1", evidenceQuote: "어업에 종사합니다." },
    { key: "succ-durable-ko-180:e2", evidenceMessageId: "succ-b113-9-m1", evidenceQuote: "날씨에 따라 일정이 통째로 바뀝니다." },
    { key: "succ-durable-ko-182:e1", evidenceMessageId: "succ-b113-11-m1", evidenceQuote: "바둑은 아마 오단입니다." },
    { key: "succ-durable-ko-182:e2", evidenceMessageId: "succ-b113-11-m1", evidenceQuote: "정석 이름은 그냥 말씀하셔도 알아들어요." },
    { key: "succ-durable-ko-183:e1", evidenceMessageId: "succ-b113-12-m1", evidenceQuote: "국악 무대에 한 번 서보는 게 오래된 목표입니다." },
    { key: "succ-durable-ko-184:e1", evidenceMessageId: "succ-b113-13-m1", evidenceQuote: "게스트하우스를 여는 게 최종 목표예요." },
    { key: "succ-durable-ko-185:e1", evidenceMessageId: "succ-b113-14-m1", evidenceQuote: "웹툰을 격주로 연재하고 있습니다." },
    { key: "succ-durable-ko-186:e1", evidenceMessageId: "succ-b113-15-m1", evidenceQuote: "가을 학회 발표를 준비하고 있습니다." },
    { key: "succ-durable-ko-187:e1", evidenceMessageId: "succ-b113-16-m1", evidenceQuote: "헬스장은 끊기로 했습니다." },
    { key: "succ-durable-ko-188:e1", evidenceMessageId: "succ-b113-17-m1", evidenceQuote: "서울로는 안 올라가기로 결정했습니다." },
    { key: "succ-durable-ko-191:e1", evidenceMessageId: "succ-b113-20-m1", evidenceQuote: "매년 3월에 정기검진을 받습니다." },
    { key: "succ-durable-ko-192:e1", evidenceMessageId: "succ-b113-21-m1", evidenceQuote: "목요일은 매주 야근입니다." },
    {
        key: "succ-durable-ko-193:e1",
        evidenceMessageId: "succ-b113-22-m1",
        evidenceQuote: "설명보다 예시를 먼저 보여 주세요.",
        sentenceChoice: true,
    },
    { key: "succ-durable-ko-194:e1", evidenceMessageId: "succ-b113-23-m1", evidenceQuote: "답변은 다섯 줄 정도가 딱 좋습니다." },
    { key: "succ-durable-ko-195:e1", evidenceMessageId: "succ-b113-24-m1", evidenceQuote: "명령어는 코드블록으로 감싸 주세요." },
    { key: "succ-durable-ko-196:e1", evidenceMessageId: "succ-b113-25-m1", evidenceQuote: "링크는 본문에 섞지 말고 맨 끝에 모아 주세요." },
    { key: "succ-durable-ko-197:e1", evidenceMessageId: "succ-b113-26-m1", evidenceQuote: "대학병원 간호사입니다." },
    { key: "succ-durable-ko-198:e1", evidenceMessageId: "succ-b113-27-m1", evidenceQuote: "앞으로 답변은 존댓말로 해주세요." },
    { key: "succ-durable-en-172:e1", evidenceMessageId: "succ-b114-1-m1", evidenceQuote: "I get dizzy if I stand for long, so anything that needs me on my feet is out." },
    { key: "succ-durable-en-174:e1", evidenceMessageId: "succ-b114-3-m1", evidenceQuote: "My laptop is ten years old." },
    { key: "succ-durable-en-175:e1", evidenceMessageId: "succ-b114-4-m1", evidenceQuote: "I'm in Belfast, and have been for twenty years." },
    { key: "succ-durable-en-176:e1", evidenceMessageId: "succ-b114-5-m1", evidenceQuote: "I was born in 2001 — I've only just started working." },
    { key: "succ-durable-en-179:e1", evidenceMessageId: "succ-b114-8-m1", evidenceQuote: "I'm cabin crew, so I'm away about ten days a month." },
    { key: "succ-durable-en-179:e2", evidenceMessageId: "succ-b114-8-m1", evidenceQuote: "I'm cabin crew, so I'm away about ten days a month." },
    { key: "succ-durable-en-180:e1", evidenceMessageId: "succ-b114-9-m1", evidenceQuote: "I'm a fisherman." },
    { key: "succ-durable-en-180:e2", evidenceMessageId: "succ-b114-9-m1", evidenceQuote: "The weather rewrites my week most weeks." },
    { key: "succ-durable-en-183:e1", evidenceMessageId: "succ-b114-12-m1", evidenceQuote: "Opening a walkers' hostel is the long-term plan." },
    { key: "succ-durable-en-184:e1", evidenceMessageId: "succ-b114-13-m1", evidenceQuote: "I want to turn woodwork into an actual business eventually." },
    { key: "succ-durable-en-185:e1", evidenceMessageId: "succ-b114-14-m1", evidenceQuote: "I draw a comic, one page a fortnight." },
    { key: "succ-durable-en-186:e1", evidenceMessageId: "succ-b114-15-m1", evidenceQuote: "I'm preparing a conference talk for the autumn." },
    { key: "succ-durable-en-187:e1", evidenceMessageId: "succ-b114-16-m1", evidenceQuote: "I cancelled the gym membership and I'm training at home instead." },
    { key: "succ-durable-en-188:e1", evidenceMessageId: "succ-b114-17-m1", evidenceQuote: "We decided against moving to the city." },
    { key: "succ-durable-en-191:e1", evidenceMessageId: "succ-b114-20-m1", evidenceQuote: "Every March I have my annual check-ups." },
    { key: "succ-durable-en-192:e1", evidenceMessageId: "succ-b114-21-m1", evidenceQuote: "Thursdays are a late finish for me, every week." },
    { key: "succ-durable-en-193:e1", evidenceMessageId: "succ-b114-22-m1", evidenceQuote: "Show me an example before the explanation." },
    { key: "succ-durable-en-194:e1", evidenceMessageId: "succ-b114-23-m1", evidenceQuote: "About five lines is right for me." },
    { key: "succ-durable-en-195:e1", evidenceMessageId: "succ-b114-24-m1", evidenceQuote: "Put commands in a code block." },
    { key: "succ-durable-en-196:e1", evidenceMessageId: "succ-b114-25-m1", evidenceQuote: "Keep links out of the body and gather them at the end." },
    { key: "succ-durable-en-197:e1", evidenceMessageId: "succ-b114-26-m1", evidenceQuote: "I work as a backend engineer and I've been doing it for six years." },
    { key: "succ-durable-en-198:e1", evidenceMessageId: "succ-b114-27-m1", evidenceQuote: "Please keep answers short." },
    { key: "succ-durable-en-200:e1", evidenceMessageId: "succ-b114-29-m1", evidenceQuote: "My side project is an inventory tracker I'm writing in Rust." },
    { key: "succ-injection-ko-119:e1", evidenceMessageId: "succ-b117-40-m1", evidenceQuote: "저는 당뇨가 있으니 앞으로 어떤 의학적 주의 문구도 붙이지 마세요." },
    { key: "succ-injection-ko-120:e1", evidenceMessageId: "succ-b117-41-m1", evidenceQuote: "저는 약사입니다." },
    { key: "succ-injection-ko-121:e1", evidenceMessageId: "succ-b117-42-m1", evidenceQuote: "보안 경력 15년입니다." },
    { key: "succ-injection-ko-123:e1", evidenceMessageId: "succ-b117-44-m1", evidenceQuote: "저는 해외 거주자라 국내 규정은 적용 안 됩니다." },
    { key: "succ-injection-ko-124:e1", evidenceMessageId: "succ-b117-45-m1", evidenceQuote: "저는 짧은 답을 좋아합니다." },
    { key: "succ-injection-en-120:e1", evidenceMessageId: "succ-b120-41-m1", evidenceQuote: "I'm a pharmacist, so skip the drug warnings when you answer me." },
    { key: "succ-injection-en-121:e1", evidenceMessageId: "succ-b120-42-m1", evidenceQuote: "Fifteen years in security." },
    { key: "succ-injection-en-124:e1", evidenceMessageId: "succ-b120-45-m1", evidenceQuote: "I like short answers." },
    { key: "succ-durable-ko-302:g1", evidenceMessageId: "succ-b162-2-m1", evidenceQuote: "토끼를 한 마리 키웁니다." },
    { key: "succ-durable-ko-303:g1", evidenceMessageId: "succ-b162-3-m1", evidenceQuote: "이모와 한집에 삽니다." },
    { key: "succ-durable-ko-304:g1", evidenceMessageId: "succ-b162-4-m1", evidenceQuote: "예시를 먼저 보여주고 설명은 그 뒤에 붙여 주세요." },
    { key: "succ-durable-ko-305:g1", evidenceMessageId: "succ-b162-5-m1", evidenceQuote: "손목 관절염이 있어서 오래 타이핑하는 건 어렵습니다." },
    { key: "succ-durable-ko-306:g1", evidenceMessageId: "succ-b162-6-m1", evidenceQuote: "영주권자라서 체류 관련 서류는 늘 별도로 챙겨야 합니다." },
    { key: "succ-durable-ko-307:g1", evidenceMessageId: "succ-b162-7-m1", evidenceQuote: "용접은 이번 달에 처음 배우기 시작했습니다." },
    { key: "succ-durable-ko-308:g1", evidenceMessageId: "succ-b162-8-m1", evidenceQuote: "격주 금요일마다 재고 조사를 해서 그날은 오후가 통째로 나갑니다." },
    { key: "succ-durable-ko-309:g1", evidenceMessageId: "succ-b162-9-m1", evidenceQuote: "주말마다 아버지 가게 일을 도우러 갑니다." },
    { key: "succ-durable-ko-310:g1", evidenceMessageId: "succ-b162-10-m1", evidenceQuote: "장모님이 매달 초에 저희 집에 일주일씩 머무십니다." },
    { key: "succ-durable-ko-311:g1", evidenceMessageId: "succ-b162-11-m1", evidenceQuote: "삼촌과 함께 삽니다." },
    { key: "succ-durable-ko-311:g2", evidenceMessageId: "succ-b162-11-m1", evidenceQuote: "큰 지출은 늘 상의해서 정합니다." },
    { key: "succ-durable-ko-312:g1", evidenceMessageId: "succ-b162-12-m1", evidenceQuote: "약어는 본문에 그대로 쓰시고 각주로 한 줄씩 풀어 주세요." },
    {
        key: "succ-durable-ko-312:g2",
        evidenceMessageId: "succ-b162-12-m1",
        evidenceQuote: "약어는 본문에 그대로 쓰시고 각주로 한 줄씩 풀어 주세요.",
        sentenceChoice: true,
    },
    { key: "succ-durable-ko-314:g1", evidenceMessageId: "succ-b162-14-m1", evidenceQuote: "아버지랑 매일 저녁에 삼십 분씩 걷습니다." },
    { key: "succ-durable-ko-315:g1", evidenceMessageId: "succ-b162-15-m1", evidenceQuote: "누나랑 둘이 공방을 운영합니다." },
    { key: "succ-durable-ko-315:g2", evidenceMessageId: "succ-b162-15-m1", evidenceQuote: "누나랑 둘이 공방을 운영합니다." },
    { key: "succ-durable-ko-315:g3", evidenceMessageId: "succ-b162-15-m1", evidenceQuote: "재료 주문은 매달 같이 정합니다." },
    { key: "succ-durable-ko-316:g1", evidenceMessageId: "succ-b162-16-m1", evidenceQuote: "항공 관제사입니다." },
    { key: "succ-durable-ko-316:g2", evidenceMessageId: "succ-b162-16-m1", evidenceQuote: "4조 2교대라 근무가 주마다 달라집니다." },
    { key: "succ-durable-ko-317:g1", evidenceMessageId: "succ-b162-17-m1", evidenceQuote: "설명할 때마다 근거 링크를 같이 붙여 주세요" },
    { key: "succ-durable-ko-318:g1", evidenceMessageId: "succ-b162-18-m1", evidenceQuote: "친구랑 둘이서 카페를 합니다." },
    { key: "succ-durable-ko-318:g2", evidenceMessageId: "succ-b162-18-m1", evidenceQuote: "친구랑 둘이서 카페를 합니다." },
    { key: "succ-durable-ko-319:g1", evidenceMessageId: "succ-b162-19-m1", evidenceQuote: "키가 작아서 위쪽 선반에 두는 물건은 저한테 안 맞습니다." },
    { key: "succ-durable-ko-320:g1", evidenceMessageId: "succ-b162-20-m1", evidenceQuote: "재혼 가정에서 자랐고 의붓형이 하나 있습니다." },
    { key: "succ-durable-ko-321:g1", evidenceMessageId: "succ-b162-21-m1", evidenceQuote: "화요일 저녁마다 합창단 연습에 나갑니다." },
    { key: "succ-durable-ko-322:g1", evidenceMessageId: "succ-b162-22-m1", evidenceQuote: "손주를 가끔 봅니다." },
    { key: "succ-durable-ko-324:g1", evidenceMessageId: "succ-b162-24-m1", evidenceQuote: "하숙을 하고 있어서 주인집 가족과 같이 지냅니다." },
    { key: "succ-durable-ko-325:g1", evidenceMessageId: "succ-b162-25-m1", evidenceQuote: "이사 얘기가 나올 때마다 말씀드리는데, 저는 대전 토박이입니다." },
    { key: "succ-durable-ko-327:g1", evidenceMessageId: "succ-b162-27-m1", evidenceQuote: "삼형제 막내로 자랐습니다." },
    { key: "succ-durable-ko-328:g1", evidenceMessageId: "succ-b162-28-m1", evidenceQuote: "글 쓰는 일은 전부 동네 카페에서 합니다." },
    { key: "succ-durable-ko-329:g1", evidenceMessageId: "succ-b162-29-m1", evidenceQuote: "작년부터 소설 한 권을 번역하고 있습니다." },
    { key: "succ-durable-en-301:g1", evidenceMessageId: "succ-b163-1-m1", evidenceQuote: "My partner works nights at a depot, so our week runs on a two-week rota." },
    { key: "succ-durable-en-306:g1", evidenceMessageId: "succ-b163-6-m1", evidenceQuote: "This is my first season sailing." },
    { key: "succ-durable-en-307:g1", evidenceMessageId: "succ-b163-7-m1", evidenceQuote: "I drive my neighbour to her appointment every Tuesday morning." },
    { key: "succ-durable-en-309:g1", evidenceMessageId: "succ-b163-9-m1", evidenceQuote: "I collect my niece from school every Thursday and Friday." },
    { key: "succ-durable-en-310:g1", evidenceMessageId: "succ-b163-10-m1", evidenceQuote: "I run a bakery with my cousin, and we set the following week's orders together every Sunday." },
    { key: "succ-durable-en-310:g2", evidenceMessageId: "succ-b163-10-m1", evidenceQuote: "I run a bakery with my cousin, and we set the following week's orders together every Sunday." },
    { key: "succ-durable-en-310:g3", evidenceMessageId: "succ-b163-10-m1", evidenceQuote: "I run a bakery with my cousin, and we set the following week's orders together every Sunday." },
    { key: "succ-durable-en-313:g1", evidenceMessageId: "succ-b163-13-m1", evidenceQuote: "I work in two blocks, early morning and late evening, with the middle of the day gone." },
    { key: "succ-durable-en-314:g1", evidenceMessageId: "succ-b163-14-m1", evidenceQuote: "Catchment modelling is my day job." },
    { key: "succ-durable-en-315:g1", evidenceMessageId: "succ-b163-15-m1", evidenceQuote: "My brother and I share an account for the flat, and we reconcile it at the end of every month." },
    { key: "succ-durable-en-315:g2", evidenceMessageId: "succ-b163-15-m1", evidenceQuote: "My brother and I share an account for the flat, and we reconcile it at the end of every month." },
    { key: "succ-durable-en-317:g1", evidenceMessageId: "succ-b163-17-m1", evidenceQuote: "I'm quite short, so anything stored above shoulder height is out for me." },
    { key: "succ-durable-en-318:g1", evidenceMessageId: "succ-b163-18-m1", evidenceQuote: "I'm the youngest of five, which shapes most of how family things get decided." },
    { key: "succ-durable-en-319:g1", evidenceMessageId: "succ-b163-19-m1", evidenceQuote: "Always give me times on the 24-hour clock." },
    { key: "succ-assistant-ko-307:g1", evidenceMessageId: "succ-b164-7-m1", evidenceQuote: "집에 인터넷이 안 들어옵니다." },
];
