-- RECON-I18N-001. The localized marketing routes moved to their own root
-- layout so `<html lang>` can come from the route's locale. A side effect is
-- that switching language away from an English page now crosses a root
-- boundary and reloads the document -- measured at about 2x, and 2.6s slower
-- on a mid-tier phone over 4G. That cost was accepted on the argument that the
-- path is rare, and nothing was measuring it. This event records each switch,
-- including whether it actually crossed the boundary, so the argument can be
-- checked rather than assumed.
ALTER TABLE "ProductAnalyticsEvent"
DROP CONSTRAINT "ProductAnalyticsEvent_name_check";

ALTER TABLE "ProductAnalyticsEvent"
ADD CONSTRAINT "ProductAnalyticsEvent_name_check"
CHECK ("eventName" IN (
  'landing_view',
  'cta_start_click',
  'pricing_view',
  'plan_selected',
  'chat_started',
  'first_response_completed',
  'multi_model_compare_completed',
  'comparison_review_viewed',
  'comparison_review_started',
  'comparison_review_completed',
  'comparison_review_failed',
  'followup_sent',
  'file_attached',
  'conversation_saved',
  'share_created',
  'signup_started',
  'signup_completed',
  'signup_page_view',
  'onboarding_shown',
  'onboarding_completed',
  'onboarding_skipped',
  'credit_limit_hit',
  'upgrade_prompt_view',
  'checkout_started',
  'checkout_failed',
  'purchase_completed',
  'promotion_pass_activated',
  'return_day_1',
  'return_day_7',
  'subscription_cancelled',
  'model_finder_viewed',
  'model_finder_started',
  'model_finder_completed',
  'model_finder_skipped',
  'recommended_model_accepted',
  'recommended_model_changed',
  'advanced_model_suggested',
  'advanced_model_selected',
  'help_opened',
  'help_article_viewed',
  'ui_help_opened',
  'sidebar_tour_started',
  'sidebar_tour_completed',
  'sidebar_tour_skipped',
  'chat_tool_menu_opened',
  'model_picker_opened',
  'model_picker_all_opened',
  'model_picker_search_used',
  'model_picker_filter_opened',
  'model_picker_filter_applied',
  'model_picker_selection_confirmed',
  'model_picker_max_reached',
  'model_picker_abandoned',
  'web_search_mode_selected',
  'web_search_suggestion_shown',
  'web_search_suggestion_accepted',
  'web_search_suggestion_declined',
  'deep_research_setup_opened',
  'deep_research_started',
  'deep_research_cancelled',
  'deep_research_completed',
  'deep_research_failed',
  'answer_sources_opened',
  'web_search_native_executed',
  'web_search_native_unsupported',
  'web_search_native_failed',
  'web_search_native_not_executed',
  'marketing_language_switched'
));
